/**
 * Generates a full products.json with 8–10 products per category.
 * Run: node generate_products.js
 */
import { readFileSync, writeFileSync } from "fs";
import { fileURLToPath } from "url";
import path from "path";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const existing = JSON.parse(
  readFileSync(path.join(__dirname, "products.json"), "utf-8"),
);

// Start new IDs after existing max
const maxId = Math.max(...existing.map((p) => Number(p._id)));
let nextId = maxId + 1;
const id = () => String(nextId++);

const newProducts = [
  // ── Fruits & Vegetables (add 5 more) ──────────────────────────────────────
  {
    _id: id(),
    name: "Fresh Onions",
    category: "Fruits & Vegetables",
    brand: "Farm Fresh",
    price: 38,
    originalPrice: 50,
    discount: "₹12 OFF",
    weight: "1 kg",
    rating: 4.2,
    ratingCount: "9k",
    tag: "Daily",
    sales: 2800,
    tags: ["onion", "vegetable", "cooking"],
    image: "https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?w=300",
    __v: 0,
  },
  {
    _id: id(),
    name: "Carrots",
    category: "Fruits & Vegetables",
    brand: "Local Farm",
    price: 42,
    originalPrice: 55,
    discount: "₹13 OFF",
    weight: "500 g",
    rating: 4.3,
    ratingCount: "4k",
    tag: "Fresh",
    sales: 1500,
    tags: ["carrot", "vegetable", "fresh"],
    image: "https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=300",
    __v: 0,
  },
  {
    _id: id(),
    name: "Green Capsicum",
    category: "Fruits & Vegetables",
    brand: "Local Farm",
    price: 55,
    originalPrice: 65,
    discount: "₹10 OFF",
    weight: "500 g",
    rating: 4.1,
    ratingCount: "3k",
    tag: null,
    sales: 1100,
    tags: ["capsicum", "vegetable", "fresh"],
    image: "https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=300",
    __v: 0,
  },
  {
    _id: id(),
    name: "Alphonso Mangoes",
    category: "Fruits & Vegetables",
    brand: "Ratnagiri",
    price: 350,
    originalPrice: 400,
    discount: "₹50 OFF",
    weight: "1 kg",
    rating: 4.9,
    ratingCount: "6k",
    tag: "Seasonal",
    sales: 2200,
    tags: ["mango", "alphonso", "fruit"],
    image: "https://images.unsplash.com/photo-1553279768-865429fa0078?w=300",
    __v: 0,
  },
  {
    _id: id(),
    name: "Fresh Ginger",
    category: "Fruits & Vegetables",
    brand: "Organic Farm",
    price: 28,
    originalPrice: 35,
    discount: "₹7 OFF",
    weight: "200 g",
    rating: 4.0,
    ratingCount: "2k",
    tag: "Organic",
    sales: 900,
    tags: ["ginger", "spice", "fresh"],
    image: "https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=300",
    __v: 0,
  },

  // ── Atta, Rice & Dals (add 4 more) ───────────────────────────────────────
  {
    _id: id(),
    name: "Chana Dal",
    category: "Atta, Rice & Dals",
    brand: "24 Mantra Organic",
    price: 135,
    originalPrice: 150,
    discount: "₹15 OFF",
    weight: "1 kg",
    rating: 4.3,
    ratingCount: "3k",
    tag: "Organic",
    sales: 1100,
    tags: ["chana", "dal", "protein"],
    image: "https://images.unsplash.com/photo-1610725664285-7c57e6eeac3f?w=300",
    __v: 0,
  },
  {
    _id: id(),
    name: "Organic Moong Dal",
    category: "Atta, Rice & Dals",
    brand: "24 Mantra",
    price: 125,
    originalPrice: 140,
    discount: "₹15 OFF",
    weight: "1 kg",
    rating: 4.4,
    ratingCount: "4k",
    tag: "Healthy",
    sales: 1400,
    tags: ["moong", "dal", "organic"],
    image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=300",
    __v: 0,
  },
  {
    _id: id(),
    name: "Sona Masoori Rice",
    category: "Atta, Rice & Dals",
    brand: "Daawat",
    price: 180,
    originalPrice: 200,
    discount: "₹20 OFF",
    weight: "2 kg",
    rating: 4.2,
    ratingCount: "5k",
    tag: "Popular",
    sales: 1900,
    tags: ["rice", "sonamasoori", "grain"],
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=300",
    __v: 0,
  },
  {
    _id: id(),
    name: "Multigrain Atta",
    category: "Atta, Rice & Dals",
    brand: "Aashirvaad",
    price: 320,
    originalPrice: 350,
    discount: "₹30 OFF",
    weight: "5 kg",
    rating: 4.5,
    ratingCount: "7k",
    tag: "Healthy",
    sales: 2300,
    tags: ["multigrain", "atta", "healthy"],
    image: "https://images.unsplash.com/photo-1574226516831-e1dff420e37e?w=300",
    __v: 0,
  },

  // ── Masala & Dry Fruits (add 4 more) ─────────────────────────────────────
  {
    _id: id(),
    name: "Cashews Premium",
    category: "Masala & Dry Fruits",
    brand: "Happilo",
    price: 380,
    originalPrice: 430,
    discount: "₹50 OFF",
    weight: "500 g",
    rating: 4.7,
    ratingCount: "6k",
    tag: "Premium",
    sales: 1800,
    tags: ["cashew", "dryfruit", "nut"],
    image: "https://images.unsplash.com/photo-1509358271058-acd22cc93898?w=300",
    __v: 0,
  },
  {
    _id: id(),
    name: "Turmeric Powder",
    category: "Masala & Dry Fruits",
    brand: "MDH",
    price: 75,
    originalPrice: 90,
    discount: "₹15 OFF",
    weight: "200 g",
    rating: 4.3,
    ratingCount: "4k",
    tag: null,
    sales: 1300,
    tags: ["turmeric", "spice", "mdh"],
    image: "https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=300",
    __v: 0,
  },
  {
    _id: id(),
    name: "Raisins Kishmish",
    category: "Masala & Dry Fruits",
    brand: "Nutraj",
    price: 195,
    originalPrice: 220,
    discount: "₹25 OFF",
    weight: "250 g",
    rating: 4.4,
    ratingCount: "3k",
    tag: "Healthy",
    sales: 1000,
    tags: ["raisin", "dryfruit", "sweet"],
    image: "https://images.unsplash.com/photo-1599599810769-bcde5a160d32?w=300",
    __v: 0,
  },
  {
    _id: id(),
    name: "Red Chilli Powder",
    category: "Masala & Dry Fruits",
    brand: "Everest",
    price: 68,
    originalPrice: 80,
    discount: "₹12 OFF",
    weight: "200 g",
    rating: 4.1,
    ratingCount: "5k",
    tag: "Spicy",
    sales: 1600,
    tags: ["chilli", "spice", "everest"],
    image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=300",
    __v: 0,
  },

  // ── Breakfast & Sauces (add 4 more) ──────────────────────────────────────
  {
    _id: id(),
    name: "Quaker Oats",
    category: "Breakfast & Sauces",
    brand: "Quaker",
    price: 155,
    originalPrice: 175,
    discount: "₹20 OFF",
    weight: "1 kg",
    rating: 4.5,
    ratingCount: "8k",
    tag: "Healthy",
    sales: 2100,
    tags: ["oats", "breakfast", "healthy"],
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=300",
    __v: 0,
  },
  {
    _id: id(),
    name: "Maggi Hot & Sweet Sauce",
    category: "Breakfast & Sauces",
    brand: "Maggi",
    price: 90,
    originalPrice: 105,
    discount: "₹15 OFF",
    weight: "400 g",
    rating: 4.3,
    ratingCount: "5k",
    tag: "Popular",
    sales: 1700,
    tags: ["sauce", "maggi", "condiment"],
    image: "https://images.unsplash.com/photo-1472476443507-c7a5948772fc?w=300",
    __v: 0,
  },
  {
    _id: id(),
    name: "Muesli Fruit & Nut",
    category: "Breakfast & Sauces",
    brand: "Saffola",
    price: 280,
    originalPrice: 320,
    discount: "₹40 OFF",
    weight: "500 g",
    rating: 4.4,
    ratingCount: "4k",
    tag: "Healthy",
    sales: 1200,
    tags: ["muesli", "breakfast", "cereal"],
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=300",
    __v: 0,
  },
  {
    _id: id(),
    name: "Creamy Peanut Butter",
    category: "Breakfast & Sauces",
    brand: "Skippy",
    price: 245,
    originalPrice: 280,
    discount: "₹35 OFF",
    weight: "462 g",
    rating: 4.6,
    ratingCount: "7k",
    tag: "Protein",
    sales: 2400,
    tags: ["peanutbutter", "spread", "protein"],
    image: "https://images.unsplash.com/photo-1574498547776-5ebe5b9c5a78?w=300",
    __v: 0,
  },

  // ── Ice Creams (add 5 more) ───────────────────────────────────────────────
  {
    _id: id(),
    name: "Chocolate Brownie Ice Cream",
    category: "Ice Creams",
    brand: "Kwality Walls",
    price: 180,
    originalPrice: 210,
    discount: "₹30 OFF",
    weight: "700 ml",
    rating: 4.7,
    ratingCount: "5k",
    tag: "Bestseller",
    sales: 2000,
    tags: ["icecream", "chocolate", "dessert"],
    image: "https://images.unsplash.com/photo-1580915411954-282cb1b0d780?w=300",
    __v: 0,
  },
  {
    _id: id(),
    name: "Butterscotch Ice Cream",
    category: "Ice Creams",
    brand: "Amul",
    price: 110,
    originalPrice: 130,
    discount: "₹20 OFF",
    weight: "500 ml",
    rating: 4.5,
    ratingCount: "4k",
    tag: null,
    sales: 1500,
    tags: ["icecream", "butterscotch", "dessert"],
    image: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=300",
    __v: 0,
  },
  {
    _id: id(),
    name: "Mango Sorbet",
    category: "Ice Creams",
    brand: "Naturals",
    price: 140,
    originalPrice: 160,
    discount: "₹20 OFF",
    weight: "500 ml",
    rating: 4.6,
    ratingCount: "3k",
    tag: "Fruity",
    sales: 1300,
    tags: ["sorbet", "mango", "icecream"],
    image: "https://images.unsplash.com/photo-1559622214-f8a9850965bb?w=300",
    __v: 0,
  },
  {
    _id: id(),
    name: "Kulfi Malai Stick",
    category: "Ice Creams",
    brand: "Vadilal",
    price: 30,
    originalPrice: 35,
    discount: "₹5 OFF",
    weight: "60 ml",
    rating: 4.4,
    ratingCount: "6k",
    tag: "Classic",
    sales: 3200,
    tags: ["kulfi", "malai", "icecream"],
    image: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=300",
    __v: 0,
  },
  {
    _id: id(),
    name: "Strawberry Ice Cream Tub",
    category: "Ice Creams",
    brand: "Baskin Robbins",
    price: 320,
    originalPrice: 360,
    discount: "₹40 OFF",
    weight: "500 ml",
    rating: 4.8,
    ratingCount: "4k",
    tag: "Premium",
    sales: 1100,
    tags: ["strawberry", "icecream", "premium"],
    image: "https://images.unsplash.com/photo-1488900128323-21503983a07e?w=300",
    __v: 0,
  },

  // ── Frozen Food (add 5 more) ──────────────────────────────────────────────
  {
    _id: id(),
    name: "Frozen Corn Kernels",
    category: "Frozen Food",
    brand: "McCain",
    price: 90,
    originalPrice: 110,
    discount: "₹20 OFF",
    weight: "500 g",
    rating: 4.2,
    ratingCount: "3k",
    tag: null,
    sales: 1000,
    tags: ["corn", "frozen", "vegetable"],
    image: "https://images.unsplash.com/photo-1551754655-cd27e38d2076?w=300",
    __v: 0,
  },
  {
    _id: id(),
    name: "Chicken Nuggets",
    category: "Frozen Food",
    brand: "Venky's",
    price: 280,
    originalPrice: 320,
    discount: "₹40 OFF",
    weight: "400 g",
    rating: 4.4,
    ratingCount: "5k",
    tag: "Bestseller",
    sales: 2100,
    tags: ["chicken", "nuggets", "frozen"],
    image: "https://images.unsplash.com/photo-1562967914-608f82629710?w=300",
    __v: 0,
  },
  {
    _id: id(),
    name: "Frozen Peas",
    category: "Frozen Food",
    brand: "Mother Dairy",
    price: 75,
    originalPrice: 90,
    discount: "₹15 OFF",
    weight: "500 g",
    rating: 4.1,
    ratingCount: "2k",
    tag: null,
    sales: 900,
    tags: ["peas", "frozen", "vegetable"],
    image: "https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=300",
    __v: 0,
  },
  {
    _id: id(),
    name: "Pizza Base Frozen",
    category: "Frozen Food",
    brand: "Pillsbury",
    price: 145,
    originalPrice: 165,
    discount: "₹20 OFF",
    weight: "2 pcs",
    rating: 4.3,
    ratingCount: "3k",
    tag: "New",
    sales: 1200,
    tags: ["pizza", "base", "frozen"],
    image: "https://images.unsplash.com/photo-1574158622682-e40e69881006?w=300",
    __v: 0,
  },
  {
    _id: id(),
    name: "Veg Momos Frozen",
    category: "Frozen Food",
    brand: "Wow Momo",
    price: 185,
    originalPrice: 210,
    discount: "₹25 OFF",
    weight: "20 pcs",
    rating: 4.5,
    ratingCount: "4k",
    tag: "Trending",
    sales: 1900,
    tags: ["momos", "frozen", "snack"],
    image: "https://images.unsplash.com/photo-1585032226651-759b368d7246?w=300",
    __v: 0,
  },

  // ── Home & Cleaning (add 5 more) ──────────────────────────────────────────
  {
    _id: id(),
    name: "Vim Dishwash Bar",
    category: "Home & Cleaning",
    brand: "Vim",
    price: 45,
    originalPrice: 52,
    discount: "₹7 OFF",
    weight: "400 g",
    rating: 4.3,
    ratingCount: "8k",
    tag: "Popular",
    sales: 2800,
    tags: ["dishwash", "cleaning", "kitchen"],
    image: "https://images.unsplash.com/photo-1585740510052-0e2486b9ce86?w=300",
    __v: 0,
  },
  {
    _id: id(),
    name: "Harpic Bathroom Cleaner",
    category: "Home & Cleaning",
    brand: "Harpic",
    price: 130,
    originalPrice: 150,
    discount: "₹20 OFF",
    weight: "500 ml",
    rating: 4.2,
    ratingCount: "5k",
    tag: null,
    sales: 1600,
    tags: ["bathroom", "cleaner", "harpic"],
    image: "https://images.unsplash.com/photo-1563453392212-326f5e854473?w=300",
    __v: 0,
  },
  {
    _id: id(),
    name: "Colin Glass Cleaner",
    category: "Home & Cleaning",
    brand: "Colin",
    price: 98,
    originalPrice: 115,
    discount: "₹17 OFF",
    weight: "500 ml",
    rating: 4.1,
    ratingCount: "3k",
    tag: null,
    sales: 1100,
    tags: ["glass", "cleaner", "colin"],
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=300",
    __v: 0,
  },
  {
    _id: id(),
    name: "Good Night Mosquito Liquid",
    category: "Home & Cleaning",
    brand: "Good Knight",
    price: 115,
    originalPrice: 130,
    discount: "₹15 OFF",
    weight: "45 ml",
    rating: 4.4,
    ratingCount: "6k",
    tag: "Essential",
    sales: 2300,
    tags: ["mosquito", "repellent", "goodknight"],
    image: "https://images.unsplash.com/photo-1563453392212-326f5e854473?w=300",
    __v: 0,
  },
  {
    _id: id(),
    name: "Scotch Brite Scrub Pad",
    category: "Home & Cleaning",
    brand: "Scotch Brite",
    price: 55,
    originalPrice: 65,
    discount: "₹10 OFF",
    weight: "3 pcs",
    rating: 4.5,
    ratingCount: "7k",
    tag: "Bestseller",
    sales: 2600,
    tags: ["scrub", "pad", "kitchen"],
    image: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=300",
    __v: 0,
  },

  // ── Toys & Games (add 5 more) ─────────────────────────────────────────────
  {
    _id: id(),
    name: "Lego Building Blocks Set",
    category: "Toys & Games",
    brand: "Lego",
    price: 1299,
    originalPrice: 1499,
    discount: "₹200 OFF",
    weight: "300 g",
    rating: 4.8,
    ratingCount: "4k",
    tag: "Popular",
    sales: 1200,
    tags: ["lego", "blocks", "kids"],
    image: "https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=300",
    __v: 0,
  },
  {
    _id: id(),
    name: "Board Game — Snakes & Ladders",
    category: "Toys & Games",
    brand: "Hasbro",
    price: 349,
    originalPrice: 399,
    discount: "₹50 OFF",
    weight: "1 unit",
    rating: 4.3,
    ratingCount: "2k",
    tag: "Family",
    sales: 800,
    tags: ["boardgame", "family", "kids"],
    image: "https://images.unsplash.com/photo-1637073849667-8f4e4e3f0c10?w=300",
    __v: 0,
  },
  {
    _id: id(),
    name: "Rubik's Cube 3x3",
    category: "Toys & Games",
    brand: "Rubiks",
    price: 249,
    originalPrice: 299,
    discount: "₹50 OFF",
    weight: "1 unit",
    rating: 4.6,
    ratingCount: "5k",
    tag: "Brainy",
    sales: 2000,
    tags: ["rubik", "puzzle", "cube"],
    image: "https://images.unsplash.com/photo-1519817914152-22d216bb9170?w=300",
    __v: 0,
  },
  {
    _id: id(),
    name: "Play-Doh Modelling Clay",
    category: "Toys & Games",
    brand: "Play-Doh",
    price: 399,
    originalPrice: 449,
    discount: "₹50 OFF",
    weight: "6 pots",
    rating: 4.5,
    ratingCount: "3k",
    tag: "Creative",
    sales: 1400,
    tags: ["playdoh", "clay", "kids"],
    image: "https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=300",
    __v: 0,
  },
  {
    _id: id(),
    name: "Nerf Gun Blaster",
    category: "Toys & Games",
    brand: "Nerf",
    price: 799,
    originalPrice: 999,
    discount: "₹200 OFF",
    weight: "1 unit",
    rating: 4.4,
    ratingCount: "3k",
    tag: "Action",
    sales: 1000,
    tags: ["nerf", "gun", "toy"],
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=300",
    __v: 0,
  },

  // ── Electronics (add 5 more) ──────────────────────────────────────────────
  {
    _id: id(),
    name: "USB-C Fast Charging Cable",
    category: "Electronics",
    brand: "Anker",
    price: 349,
    originalPrice: 399,
    discount: "₹50 OFF",
    weight: "1 unit",
    rating: 4.5,
    ratingCount: "10k",
    tag: "Bestseller",
    sales: 3200,
    tags: ["cable", "usbc", "charger"],
    image: "https://images.unsplash.com/photo-1601597111158-2fceff292cdc?w=300",
    __v: 0,
  },
  {
    _id: id(),
    name: "Portable Power Bank 20000mAh",
    category: "Electronics",
    brand: "Mi",
    price: 1499,
    originalPrice: 1799,
    discount: "₹300 OFF",
    weight: "440 g",
    rating: 4.6,
    ratingCount: "8k",
    tag: "Popular",
    sales: 2500,
    tags: ["powerbank", "mi", "battery"],
    image: "https://images.unsplash.com/photo-1609592806596-b3b524c7c48e?w=300",
    __v: 0,
  },
  {
    _id: id(),
    name: "Smart LED Bulb 9W",
    category: "Electronics",
    brand: "Philips",
    price: 249,
    originalPrice: 299,
    discount: "₹50 OFF",
    weight: "1 unit",
    rating: 4.3,
    ratingCount: "5k",
    tag: "Energy Saver",
    sales: 1800,
    tags: ["bulb", "led", "philips"],
    image: "https://images.unsplash.com/photo-1550408483-bafa35b0a5af?w=300",
    __v: 0,
  },
  {
    _id: id(),
    name: "Laptop Stand Adjustable",
    category: "Electronics",
    brand: "AmazonBasics",
    price: 899,
    originalPrice: 1099,
    discount: "₹200 OFF",
    weight: "800 g",
    rating: 4.4,
    ratingCount: "4k",
    tag: "WFH",
    sales: 1400,
    tags: ["laptop", "stand", "accessories"],
    image: "https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=300",
    __v: 0,
  },
  {
    _id: id(),
    name: "Wireless Mouse",
    category: "Electronics",
    brand: "Logitech",
    price: 699,
    originalPrice: 899,
    discount: "₹200 OFF",
    weight: "100 g",
    rating: 4.7,
    ratingCount: "9k",
    tag: "Trending",
    sales: 2800,
    tags: ["mouse", "logitech", "wireless"],
    image: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=300",
    __v: 0,
  },

  // ── Beauty & Personal Care (add 5 more) ───────────────────────────────────
  {
    _id: id(),
    name: "Dove Body Lotion",
    category: "Beauty & Personal Care",
    brand: "Dove",
    price: 220,
    originalPrice: 255,
    discount: "₹35 OFF",
    weight: "400 ml",
    rating: 4.5,
    ratingCount: "7k",
    tag: "Moisturising",
    sales: 2300,
    tags: ["lotion", "dove", "skincare"],
    image: "https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=300",
    __v: 0,
  },
  {
    _id: id(),
    name: "Sunscreen SPF 50 PA+++",
    category: "Beauty & Personal Care",
    brand: "Lakme",
    price: 295,
    originalPrice: 350,
    discount: "₹55 OFF",
    weight: "50 ml",
    rating: 4.4,
    ratingCount: "6k",
    tag: "UV Protection",
    sales: 1900,
    tags: ["sunscreen", "spf50", "skincare"],
    image: "https://images.unsplash.com/photo-1580870069867-74c57ee1bb07?w=300",
    __v: 0,
  },
  {
    _id: id(),
    name: "Head & Shoulders Shampoo",
    category: "Beauty & Personal Care",
    brand: "Head & Shoulders",
    price: 315,
    originalPrice: 370,
    discount: "₹55 OFF",
    weight: "340 ml",
    rating: 4.3,
    ratingCount: "5k",
    tag: "Anti Dandruff",
    sales: 1600,
    tags: ["shampoo", "dandruff", "hair"],
    image: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=300",
    __v: 0,
  },
  {
    _id: id(),
    name: "Gillette Shaving Gel",
    category: "Beauty & Personal Care",
    brand: "Gillette",
    price: 185,
    originalPrice: 210,
    discount: "₹25 OFF",
    weight: "200 g",
    rating: 4.4,
    ratingCount: "4k",
    tag: null,
    sales: 1300,
    tags: ["shaving", "gel", "gillette"],
    image: "https://images.unsplash.com/photo-1512163143273-bde0e3cc7407?w=300",
    __v: 0,
  },
  {
    _id: id(),
    name: "Himalaya Face Wash Neem",
    category: "Beauty & Personal Care",
    brand: "Himalaya",
    price: 135,
    originalPrice: 160,
    discount: "₹25 OFF",
    weight: "150 ml",
    rating: 4.5,
    ratingCount: "9k",
    tag: "Bestseller",
    sales: 3100,
    tags: ["facewash", "neem", "himalaya"],
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=300",
    __v: 0,
  },

  // ── Fashion (add 5 more) ──────────────────────────────────────────────────
  {
    _id: id(),
    name: "Women Kurti Floral Print",
    category: "Fashion",
    brand: "Biba",
    price: 899,
    originalPrice: 1199,
    discount: "₹300 OFF",
    weight: "1 unit",
    rating: 4.3,
    ratingCount: "2k",
    tag: "Trending",
    sales: 900,
    tags: ["kurti", "women", "fashion"],
    image: "https://images.unsplash.com/photo-1594938298603-c8148c4b4057?w=300",
    __v: 0,
  },
  {
    _id: id(),
    name: "Running Shoes Men",
    category: "Fashion",
    brand: "Nike",
    price: 2499,
    originalPrice: 3499,
    discount: "₹1000 OFF",
    weight: "1 pair",
    rating: 4.6,
    ratingCount: "5k",
    tag: "Sport",
    sales: 1800,
    tags: ["shoes", "nike", "running"],
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=300",
    __v: 0,
  },
  {
    _id: id(),
    name: "Casual Denim Jeans",
    category: "Fashion",
    brand: "Levi's",
    price: 1899,
    originalPrice: 2499,
    discount: "₹600 OFF",
    weight: "1 unit",
    rating: 4.5,
    ratingCount: "4k",
    tag: "Classic",
    sales: 1500,
    tags: ["jeans", "denim", "levis"],
    image: "https://images.unsplash.com/photo-1542272454315-4c01d7abdf4a?w=300",
    __v: 0,
  },
  {
    _id: id(),
    name: "Silk Saree Kanjivaram",
    category: "Fashion",
    brand: "Craftsvilla",
    price: 3299,
    originalPrice: 4500,
    discount: "₹1201 OFF",
    weight: "1 unit",
    rating: 4.7,
    ratingCount: "1k",
    tag: "Ethnic",
    sales: 500,
    tags: ["saree", "silk", "ethnic"],
    image: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=300",
    __v: 0,
  },
  {
    _id: id(),
    name: "Sports Shorts Men",
    category: "Fashion",
    brand: "Adidas",
    price: 699,
    originalPrice: 899,
    discount: "₹200 OFF",
    weight: "1 unit",
    rating: 4.3,
    ratingCount: "3k",
    tag: null,
    sales: 1200,
    tags: ["shorts", "adidas", "sports"],
    image: "https://images.unsplash.com/photo-1556906781-9a414e2a7735?w=300",
    __v: 0,
  },

  // ── Beverages (8 new) ─────────────────────────────────────────────────────
  {
    _id: id(),
    name: "Coca-Cola 2L",
    category: "Beverages",
    brand: "Coca-Cola",
    price: 95,
    originalPrice: 110,
    discount: "₹15 OFF",
    weight: "2 L",
    rating: 4.2,
    ratingCount: "10k",
    tag: "Popular",
    sales: 3500,
    tags: ["cola", "soda", "cold drink"],
    image: "https://images.unsplash.com/photo-1554866585-cd94860890b7?w=300",
    __v: 0,
  },
  {
    _id: id(),
    name: "Tropicana Orange Juice",
    category: "Beverages",
    brand: "Tropicana",
    price: 99,
    originalPrice: 115,
    discount: "₹16 OFF",
    weight: "1 L",
    rating: 4.4,
    ratingCount: "8k",
    tag: "Healthy",
    sales: 2700,
    tags: ["juice", "orange", "tropicana"],
    image: "https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=300",
    __v: 0,
  },
  {
    _id: id(),
    name: "Bisleri Mineral Water 1L",
    category: "Beverages",
    brand: "Bisleri",
    price: 20,
    originalPrice: 20,
    discount: "MRP",
    weight: "1 L",
    rating: 4.0,
    ratingCount: "5k",
    tag: null,
    sales: 5000,
    tags: ["water", "mineral", "bisleri"],
    image: "https://images.unsplash.com/photo-1548839140-29a749e1cf4d?w=300",
    __v: 0,
  },
  {
    _id: id(),
    name: "Red Bull Energy Drink",
    category: "Beverages",
    brand: "Red Bull",
    price: 125,
    originalPrice: 130,
    discount: "₹5 OFF",
    weight: "250 ml",
    rating: 4.3,
    ratingCount: "6k",
    tag: "Energy",
    sales: 2100,
    tags: ["energy", "redbull", "drink"],
    image: "https://images.unsplash.com/photo-1581287053822-fd7bf4f4bfec?w=300",
    __v: 0,
  },
  {
    _id: id(),
    name: "Lipton Green Tea Bags",
    category: "Beverages",
    brand: "Lipton",
    price: 150,
    originalPrice: 175,
    discount: "₹25 OFF",
    weight: "100 bags",
    rating: 4.4,
    ratingCount: "7k",
    tag: "Green Tea",
    sales: 2300,
    tags: ["greentea", "lipton", "healthy"],
    image: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=300",
    __v: 0,
  },
  {
    _id: id(),
    name: "Nescafe Classic Coffee",
    category: "Beverages",
    brand: "Nescafe",
    price: 210,
    originalPrice: 240,
    discount: "₹30 OFF",
    weight: "95 g",
    rating: 4.6,
    ratingCount: "9k",
    tag: "Bestseller",
    sales: 3000,
    tags: ["coffee", "nescafe", "instant"],
    image: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=300",
    __v: 0,
  },
  {
    _id: id(),
    name: "Sprite Lemon Lime 2L",
    category: "Beverages",
    brand: "Sprite",
    price: 90,
    originalPrice: 105,
    discount: "₹15 OFF",
    weight: "2 L",
    rating: 4.1,
    ratingCount: "6k",
    tag: null,
    sales: 2800,
    tags: ["sprite", "soda", "lemon"],
    image: "https://images.unsplash.com/photo-1625772299848-391b6a87d7b3?w=300",
    __v: 0,
  },
  {
    _id: id(),
    name: "Maaza Mango Drink 600ml",
    category: "Beverages",
    brand: "Maaza",
    price: 40,
    originalPrice: 45,
    discount: "₹5 OFF",
    weight: "600 ml",
    rating: 4.3,
    ratingCount: "8k",
    tag: "Mango",
    sales: 3100,
    tags: ["maaza", "mango", "juice"],
    image: "https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=300",
    __v: 0,
  },

  // ── Dairy, Bread & Eggs (8 new) ───────────────────────────────────────────
  {
    _id: id(),
    name: "Amul Gold Full Cream Milk 1L",
    category: "Dairy, Bread & Eggs",
    brand: "Amul",
    price: 68,
    originalPrice: 70,
    discount: "₹2 OFF",
    weight: "1 L",
    rating: 4.7,
    ratingCount: "20k",
    tag: "Bestseller",
    sales: 6000,
    tags: ["milk", "amul", "dairy"],
    image: "https://images.unsplash.com/photo-1563636619-e9143da7973b?w=300",
    __v: 0,
  },
  {
    _id: id(),
    name: "Brittania Brown Bread",
    category: "Dairy, Bread & Eggs",
    brand: "Britannia",
    price: 48,
    originalPrice: 55,
    discount: "₹7 OFF",
    weight: "400 g",
    rating: 4.4,
    ratingCount: "10k",
    tag: "Healthy",
    sales: 4200,
    tags: ["bread", "brown", "britannia"],
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=300",
    __v: 0,
  },
  {
    _id: id(),
    name: "Farm Fresh Eggs Tray",
    category: "Dairy, Bread & Eggs",
    brand: "Eggoz",
    price: 95,
    originalPrice: 105,
    discount: "₹10 OFF",
    weight: "12 pcs",
    rating: 4.6,
    ratingCount: "8k",
    tag: "Fresh",
    sales: 3800,
    tags: ["eggs", "fresh", "protein"],
    image: "https://images.unsplash.com/photo-1569288063643-5d29ad64df09?w=300",
    __v: 0,
  },
  {
    _id: id(),
    name: "Amul Salted Butter",
    category: "Dairy, Bread & Eggs",
    brand: "Amul",
    price: 55,
    originalPrice: 60,
    discount: "₹5 OFF",
    weight: "100 g",
    rating: 4.5,
    ratingCount: "12k",
    tag: "Classic",
    sales: 4500,
    tags: ["butter", "amul", "dairy"],
    image: "https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=300",
    __v: 0,
  },
  {
    _id: id(),
    name: "Mother Dairy Curd 400g",
    category: "Dairy, Bread & Eggs",
    brand: "Mother Dairy",
    price: 42,
    originalPrice: 48,
    discount: "₹6 OFF",
    weight: "400 g",
    rating: 4.4,
    ratingCount: "7k",
    tag: "Probiotic",
    sales: 2900,
    tags: ["curd", "yogurt", "dairy"],
    image: "https://images.unsplash.com/photo-1571212515416-fef01fc43637?w=300",
    __v: 0,
  },
  {
    _id: id(),
    name: "Amul Processed Cheese Slices",
    category: "Dairy, Bread & Eggs",
    brand: "Amul",
    price: 115,
    originalPrice: 130,
    discount: "₹15 OFF",
    weight: "200 g",
    rating: 4.5,
    ratingCount: "9k",
    tag: "Popular",
    sales: 3400,
    tags: ["cheese", "amul", "dairy"],
    image: "https://images.unsplash.com/photo-1552767059-ce182ead6c1b?w=300",
    __v: 0,
  },
  {
    _id: id(),
    name: "Multigrain Bread Loaf",
    category: "Dairy, Bread & Eggs",
    brand: "Harvest Gold",
    price: 55,
    originalPrice: 65,
    discount: "₹10 OFF",
    weight: "500 g",
    rating: 4.3,
    ratingCount: "5k",
    tag: "Healthy",
    sales: 1900,
    tags: ["bread", "multigrain", "healthy"],
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=300",
    __v: 0,
  },
  {
    _id: id(),
    name: "Amul Masti Dahi 1kg",
    category: "Dairy, Bread & Eggs",
    brand: "Amul",
    price: 78,
    originalPrice: 88,
    discount: "₹10 OFF",
    weight: "1 kg",
    rating: 4.6,
    ratingCount: "6k",
    tag: "Creamy",
    sales: 2600,
    tags: ["dahi", "curd", "amul"],
    image: "https://images.unsplash.com/photo-1571212515416-fef01fc43637?w=300",
    __v: 0,
  },

  // ── Instant Food (8 new) ──────────────────────────────────────────────────
  {
    _id: id(),
    name: "Maggi 2-Minute Noodles",
    category: "Instant Food",
    brand: "Maggi",
    price: 14,
    originalPrice: 14,
    discount: "MRP",
    weight: "70 g",
    rating: 4.5,
    ratingCount: "25k",
    tag: "Bestseller",
    sales: 8000,
    tags: ["maggi", "noodles", "instant"],
    image: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=300",
    __v: 0,
  },
  {
    _id: id(),
    name: "Knorr Tomato Soup",
    category: "Instant Food",
    brand: "Knorr",
    price: 55,
    originalPrice: 62,
    discount: "₹7 OFF",
    weight: "53 g",
    rating: 4.3,
    ratingCount: "6k",
    tag: "Classic",
    sales: 2200,
    tags: ["soup", "tomato", "knorr"],
    image: "https://images.unsplash.com/photo-1547592180-85f173990554?w=300",
    __v: 0,
  },
  {
    _id: id(),
    name: "Poha Ready to Cook",
    category: "Instant Food",
    brand: "MTR",
    price: 45,
    originalPrice: 52,
    discount: "₹7 OFF",
    weight: "80 g",
    rating: 4.2,
    ratingCount: "4k",
    tag: "Breakfast",
    sales: 1500,
    tags: ["poha", "instant", "mtr"],
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=300",
    __v: 0,
  },
  {
    _id: id(),
    name: "Cup Noodles Chicken",
    category: "Instant Food",
    brand: "Nissin",
    price: 30,
    originalPrice: 35,
    discount: "₹5 OFF",
    weight: "70 g",
    rating: 4.1,
    ratingCount: "5k",
    tag: null,
    sales: 2800,
    tags: ["noodles", "cup", "instant"],
    image: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=300",
    __v: 0,
  },
  {
    _id: id(),
    name: "Upma Rava Instant Mix",
    category: "Instant Food",
    brand: "MTR",
    price: 65,
    originalPrice: 75,
    discount: "₹10 OFF",
    weight: "200 g",
    rating: 4.3,
    ratingCount: "3k",
    tag: "Breakfast",
    sales: 1300,
    tags: ["upma", "instant", "mtr"],
    image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=300",
    __v: 0,
  },
  {
    _id: id(),
    name: "Dal Makhani Ready to Eat",
    category: "Instant Food",
    brand: "Kitchens of India",
    price: 120,
    originalPrice: 140,
    discount: "₹20 OFF",
    weight: "285 g",
    rating: 4.4,
    ratingCount: "4k",
    tag: "Tasty",
    sales: 1700,
    tags: ["dal", "readytoeat", "instant"],
    image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=300",
    __v: 0,
  },
  {
    _id: id(),
    name: "Pasta Instant Masala",
    category: "Instant Food",
    brand: "Ching's Secret",
    price: 25,
    originalPrice: 28,
    discount: "₹3 OFF",
    weight: "60 g",
    rating: 4.0,
    ratingCount: "5k",
    tag: null,
    sales: 2100,
    tags: ["pasta", "instant", "masala"],
    image: "https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=300",
    __v: 0,
  },
  {
    _id: id(),
    name: "Biryani Instant Mix",
    category: "Instant Food",
    brand: "Shan Masala",
    price: 85,
    originalPrice: 100,
    discount: "₹15 OFF",
    weight: "50 g",
    rating: 4.6,
    ratingCount: "3k",
    tag: "Popular",
    sales: 1900,
    tags: ["biryani", "mix", "instant"],
    image: "https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=300",
    __v: 0,
  },

  // ── Snacks & Munchies (8 new) ─────────────────────────────────────────────
  {
    _id: id(),
    name: "Lay's Classic Salted Chips",
    category: "Snacks & Munchies",
    brand: "Lays",
    price: 20,
    originalPrice: 20,
    discount: "MRP",
    weight: "52 g",
    rating: 4.3,
    ratingCount: "15k",
    tag: "Popular",
    sales: 6000,
    tags: ["chips", "lays", "snack"],
    image: "https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=300",
    __v: 0,
  },
  {
    _id: id(),
    name: "Kurkure Masala Munch",
    category: "Snacks & Munchies",
    brand: "Kurkure",
    price: 20,
    originalPrice: 20,
    discount: "MRP",
    weight: "65 g",
    rating: 4.4,
    ratingCount: "12k",
    tag: "Spicy",
    sales: 5500,
    tags: ["kurkure", "snack", "masala"],
    image: "https://images.unsplash.com/photo-1575389583827-1e56d22f4b71?w=300",
    __v: 0,
  },
  {
    _id: id(),
    name: "Haldiram's Aloo Bhujia",
    category: "Snacks & Munchies",
    brand: "Haldirams",
    price: 115,
    originalPrice: 130,
    discount: "₹15 OFF",
    weight: "400 g",
    rating: 4.5,
    ratingCount: "9k",
    tag: "Bestseller",
    sales: 3200,
    tags: ["bhujia", "haldirams", "namkeen"],
    image: "https://images.unsplash.com/photo-1575389583827-1e56d22f4b71?w=300",
    __v: 0,
  },
  {
    _id: id(),
    name: "Oreo Original Biscuits",
    category: "Snacks & Munchies",
    brand: "Oreo",
    price: 60,
    originalPrice: 65,
    discount: "₹5 OFF",
    weight: "300 g",
    rating: 4.6,
    ratingCount: "11k",
    tag: "Classic",
    sales: 4500,
    tags: ["oreo", "biscuit", "cookies"],
    image: "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=300",
    __v: 0,
  },
  {
    _id: id(),
    name: "Britannia Good Day Cashew",
    category: "Snacks & Munchies",
    brand: "Britannia",
    price: 35,
    originalPrice: 40,
    discount: "₹5 OFF",
    weight: "100 g",
    rating: 4.3,
    ratingCount: "8k",
    tag: null,
    sales: 3000,
    tags: ["biscuit", "cashew", "britannia"],
    image: "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=300",
    __v: 0,
  },
  {
    _id: id(),
    name: "Cornitos Nachos Cheese",
    category: "Snacks & Munchies",
    brand: "Cornitos",
    price: 90,
    originalPrice: 100,
    discount: "₹10 OFF",
    weight: "150 g",
    rating: 4.2,
    ratingCount: "4k",
    tag: "Cheesy",
    sales: 1800,
    tags: ["nachos", "cheese", "snack"],
    image: "https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=300",
    __v: 0,
  },
  {
    _id: id(),
    name: "Mixed Dry Fruits Trail Mix",
    category: "Snacks & Munchies",
    brand: "Happilo",
    price: 299,
    originalPrice: 349,
    discount: "₹50 OFF",
    weight: "200 g",
    rating: 4.5,
    ratingCount: "5k",
    tag: "Healthy",
    sales: 2000,
    tags: ["dryfruit", "trailmix", "healthy"],
    image: "https://images.unsplash.com/photo-1606923829579-0cb981a83e2c?w=300",
    __v: 0,
  },
  {
    _id: id(),
    name: "Parle-G Biscuits",
    category: "Snacks & Munchies",
    brand: "Parle",
    price: 5,
    originalPrice: 5,
    discount: "MRP",
    weight: "75 g",
    rating: 4.6,
    ratingCount: "30k",
    tag: "Iconic",
    sales: 10000,
    tags: ["parleg", "biscuit", "parle"],
    image: "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=300",
    __v: 0,
  },
];

// Merge and write
const allProducts = [...existing, ...newProducts];
writeFileSync(
  path.join(__dirname, "products.json"),
  JSON.stringify(allProducts, null, 2),
  "utf-8",
);

console.log(`✅ Written ${allProducts.length} products to products.json`);
const cats = [...new Set(allProducts.map((p) => p.category))].sort();
console.log("📦 Categories:", cats);
