/**
 * Seed Nepal-context products into MongoDB.
 * Run: node seed_nepal_products.js
 *
 * Prices are in NPR (Nepalese Rupees).
 * Categories match the app's existing category system.
 */

import mongoose from "mongoose";
import dotenv from "dotenv";
import { fileURLToPath } from "url";
import path from "path";

dotenv.config({
  path: path.join(path.dirname(fileURLToPath(import.meta.url)), ".env"),
});

const ProductSchema = new mongoose.Schema({
  _id: String,
  name: { type: String, required: true },
  category: { type: String, required: true },
  brand: String,
  price: { type: Number, required: true },
  originalPrice: { type: Number, required: true },
  discount: { type: String, default: "MRP" },
  weight: { type: String, default: "" },
  rating: { type: Number, default: 4.0 },
  ratingCount: { type: String, default: "0" },
  tag: { type: String, default: null },
  sales: { type: Number, default: 0 },
  tags: [String],
  image: { type: String, default: "" },
  stock: { type: Number, default: 50 },
});

const Product = mongoose.model("Product", ProductSchema);

const products = [
  // ── Dairy ─────────────────────────────────────────────────────────────────
  {
    _id: "np_d1",
    name: "Dairy Development Toned Milk 1L",
    category: "Dairy",
    brand: "Dairy Development Corporation",
    price: 72,
    originalPrice: 75,
    discount: "Rs 3 OFF",
    weight: "1 L",
    rating: 4.5,
    ratingCount: "3.2k",
    tag: "Daily",
    sales: 3200,
    tags: ["milk", "dairy", "ddc", "toned milk", "daily"],
    image: "https://images.unsplash.com/photo-1563636619-e9143da7973b?w=400",
    stock: 100,
  },
  {
    _id: "np_d2",
    name: "Sujal Fresh Dahi (Curd) 400g",
    category: "Dairy",
    brand: "Sujal",
    price: 65,
    originalPrice: 70,
    discount: "Rs 5 OFF",
    weight: "400 g",
    rating: 4.4,
    ratingCount: "1.8k",
    tag: "Fresh",
    sales: 1800,
    tags: ["curd", "dahi", "yogurt", "sujal", "dairy"],
    image: "https://images.unsplash.com/photo-1567093322916-5a34e4e9cd64?w=400",
    stock: 60,
  },
  {
    _id: "np_d3",
    name: "Amul Butter 100g",
    category: "Dairy",
    brand: "Amul",
    price: 58,
    originalPrice: 62,
    discount: "Rs 4 OFF",
    weight: "100 g",
    rating: 4.6,
    ratingCount: "5.1k",
    tag: null,
    sales: 2500,
    tags: ["butter", "amul", "dairy", "bread spread"],
    image: "https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=400",
    stock: 80,
  },
  {
    _id: "np_d4",
    name: "Farm Eggs (White) – Pack of 6",
    category: "Dairy",
    brand: "Local Farm",
    price: 85,
    originalPrice: 90,
    discount: "Rs 5 OFF",
    weight: "6 pcs",
    rating: 4.3,
    ratingCount: "2.4k",
    tag: "Fresh",
    sales: 2200,
    tags: ["eggs", "protein", "breakfast", "farm fresh"],
    image: "https://images.unsplash.com/photo-1498654200943-1088dd4438ae?w=400",
    stock: 120,
  },
  {
    _id: "np_d5",
    name: "Patanjali Cow Ghee 500ml",
    category: "Dairy",
    brand: "Patanjali",
    price: 350,
    originalPrice: 390,
    discount: "10% OFF",
    weight: "500 ml",
    rating: 4.5,
    ratingCount: "4.0k",
    tag: "Popular",
    sales: 2800,
    tags: ["ghee", "cow ghee", "patanjali", "cooking", "puja"],
    image: "https://images.unsplash.com/photo-1631209121750-a9f656d8dd95?w=400",
    stock: 70,
  },

  // ── Bakery ─────────────────────────────────────────────────────────────────
  {
    _id: "np_b1",
    name: "Gandaki Noodles – Instant Chau Chau (5 pack)",
    category: "Bakery",
    brand: "Gandaki Noodles",
    price: 110,
    originalPrice: 125,
    discount: "Rs 15 OFF",
    weight: "5 × 75 g",
    rating: 4.7,
    ratingCount: "8.5k",
    tag: "Bestseller",
    sales: 8500,
    tags: ["chau chau", "noodles", "instant", "gandaki", "snack"],
    image: "https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=400",
    stock: 200,
  },
  {
    _id: "np_b2",
    name: "Safa White Bread Loaf",
    category: "Bakery",
    brand: "Safa Bread",
    price: 60,
    originalPrice: 65,
    discount: "Rs 5 OFF",
    weight: "400 g",
    rating: 4.2,
    ratingCount: "1.2k",
    tag: null,
    sales: 1500,
    tags: ["bread", "white bread", "loaf", "safa", "bakery"],
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400",
    stock: 60,
  },
  {
    _id: "np_b3",
    name: "Annapurna Sel Roti Mix 500g",
    category: "Bakery",
    brand: "Annapurna",
    price: 120,
    originalPrice: 135,
    discount: "Rs 15 OFF",
    weight: "500 g",
    rating: 4.4,
    ratingCount: "900",
    tag: "Festive",
    sales: 900,
    tags: ["sel roti", "sel", "rice bread", "festive", "annapurna"],
    image: "https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=400",
    stock: 40,
  },

  // ── Grocery ─────────────────────────────────────────────────────────────────
  {
    _id: "np_g1",
    name: "Mustard Oil (Sarso Tel) 1L",
    category: "Grocery",
    brand: "Dabur",
    price: 220,
    originalPrice: 245,
    discount: "Rs 25 OFF",
    weight: "1 L",
    rating: 4.4,
    ratingCount: "3.7k",
    tag: "Popular",
    sales: 3700,
    tags: ["sarso tel", "mustard oil", "cooking oil", "dabur"],
    image: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400",
    stock: 90,
  },
  {
    _id: "np_g2",
    name: "Himalayan Pink Rock Salt 1kg",
    category: "Grocery",
    brand: "Himalayan",
    price: 130,
    originalPrice: 150,
    discount: "Rs 20 OFF",
    weight: "1 kg",
    rating: 4.6,
    ratingCount: "2.3k",
    tag: "Natural",
    sales: 2300,
    tags: ["salt", "rock salt", "himalayan salt", "pink salt", "cooking"],
    image: "https://images.unsplash.com/photo-1514668460573-777b66e7d7bb?w=400",
    stock: 150,
  },
  {
    _id: "np_g3",
    name: "Kaalo Daal (Black Lentils) 500g",
    category: "Grocery",
    brand: "Local Farm",
    price: 95,
    originalPrice: 110,
    discount: "Rs 15 OFF",
    weight: "500 g",
    rating: 4.3,
    ratingCount: "1.1k",
    tag: null,
    sales: 1100,
    tags: ["daal", "lentils", "black lentil", "dal", "protein"],
    image: "https://images.unsplash.com/photo-1585090018231-6f0a8085d7b6?w=400",
    stock: 80,
  },
  {
    _id: "np_g4",
    name: "Basmati Chaamal (Rice) 2kg",
    category: "Grocery",
    brand: "Doon Valley",
    price: 290,
    originalPrice: 320,
    discount: "Rs 30 OFF",
    weight: "2 kg",
    rating: 4.5,
    ratingCount: "4.5k",
    tag: "Bestseller",
    sales: 4500,
    tags: ["rice", "chaamal", "basmati", "staple", "cooking"],
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400",
    stock: 120,
  },
  {
    _id: "np_g5",
    name: "Wai Wai Noodles – Chicken (5 pack)",
    category: "Grocery",
    brand: "Wai Wai",
    price: 100,
    originalPrice: 115,
    discount: "Rs 15 OFF",
    weight: "5 × 75 g",
    rating: 4.8,
    ratingCount: "12k",
    tag: "🔥 Trending",
    sales: 12000,
    tags: ["wai wai", "noodles", "instant noodles", "chicken", "snack"],
    image: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=400",
    stock: 300,
  },
  {
    _id: "np_g6",
    name: "CG Sunflower Oil 1L",
    category: "Grocery",
    brand: "Chaudhary Group",
    price: 195,
    originalPrice: 215,
    discount: "Rs 20 OFF",
    weight: "1 L",
    rating: 4.3,
    ratingCount: "2.8k",
    tag: null,
    sales: 2800,
    tags: ["sunflower oil", "cooking oil", "cg", "chaudhary"],
    image: "https://images.unsplash.com/photo-1474987031901-d499c4643e2e?w=400",
    stock: 100,
  },
  {
    _id: "np_g7",
    name: "Himalayan Green Tea 25 bags",
    category: "Grocery",
    brand: "Himalayan Tea",
    price: 180,
    originalPrice: 200,
    discount: "10% OFF",
    weight: "25 bags",
    rating: 4.5,
    ratingCount: "3.5k",
    tag: "Organic",
    sales: 3500,
    tags: ["green tea", "tea", "himalayan", "organic", "health"],
    image: "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=400",
    stock: 150,
  },
  {
    _id: "np_g8",
    name: "Dhaka Coffee – Ground 200g",
    category: "Grocery",
    brand: "Himalayan Java",
    price: 450,
    originalPrice: 500,
    discount: "10% OFF",
    weight: "200 g",
    rating: 4.6,
    ratingCount: "1.8k",
    tag: "Local",
    sales: 1800,
    tags: ["coffee", "ground coffee", "nepal coffee", "himalayan java"],
    image: "https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=400",
    stock: 60,
  },

  // ── Fruits & Vegetables ──────────────────────────────────────────────────
  {
    _id: "np_fv1",
    name: "Palunggo (Spinach) Fresh Bunch",
    category: "Fruits & Vegetables",
    brand: "Local Farm",
    price: 30,
    originalPrice: 40,
    discount: "Rs 10 OFF",
    weight: "250 g",
    rating: 4.4,
    ratingCount: "700",
    tag: "Fresh",
    sales: 1200,
    tags: ["spinach", "palunggo", "greens", "vegetable", "fresh"],
    image: "https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=400",
    stock: 50,
  },
  {
    _id: "np_fv2",
    name: "Golbheda (Tomato) 500g",
    category: "Fruits & Vegetables",
    brand: "Local Farm",
    price: 45,
    originalPrice: 55,
    discount: "Rs 10 OFF",
    weight: "500 g",
    rating: 4.3,
    ratingCount: "1.5k",
    tag: "Daily",
    sales: 2500,
    tags: ["tomato", "golbheda", "vegetable", "salad", "cooking"],
    image: "https://images.unsplash.com/photo-1558818498-28c1e002b655?w=400",
    stock: 80,
  },
  {
    _id: "np_fv3",
    name: "Pyaj (Onion) 1kg",
    category: "Fruits & Vegetables",
    brand: "Local Farm",
    price: 55,
    originalPrice: 65,
    discount: "Rs 10 OFF",
    weight: "1 kg",
    rating: 4.2,
    ratingCount: "3.2k",
    tag: null,
    sales: 3200,
    tags: ["onion", "pyaj", "vegetable", "cooking", "daily"],
    image: "https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?w=400",
    stock: 120,
  },
  {
    _id: "np_fv4",
    name: "Kagati (Lemon) Pack of 6",
    category: "Fruits & Vegetables",
    brand: "Local Farm",
    price: 35,
    originalPrice: 45,
    discount: "Rs 10 OFF",
    weight: "6 pcs",
    rating: 4.4,
    ratingCount: "1.1k",
    tag: "Fresh",
    sales: 1800,
    tags: ["lemon", "kagati", "citrus", "nimbu", "fresh"],
    image: "https://images.unsplash.com/photo-1582287014914-1db3a8b3e4e5?w=400",
    stock: 60,
  },
  {
    _id: "np_fv5",
    name: "Kera (Banana) – 6 pcs",
    category: "Fruits & Vegetables",
    brand: "Local Farm",
    price: 50,
    originalPrice: 60,
    discount: "Rs 10 OFF",
    weight: "6 pcs",
    rating: 4.5,
    ratingCount: "2.8k",
    tag: "Daily",
    sales: 3000,
    tags: ["banana", "kera", "fruit", "fresh", "daily"],
    image: "https://images.unsplash.com/photo-1603833665858-e61d17a86224?w=400",
    stock: 100,
  },
  {
    _id: "np_fv6",
    name: "Aduwa (Ginger) 250g",
    category: "Fruits & Vegetables",
    brand: "Local Farm",
    price: 40,
    originalPrice: 50,
    discount: "Rs 10 OFF",
    weight: "250 g",
    rating: 4.3,
    ratingCount: "900",
    tag: null,
    sales: 1000,
    tags: ["ginger", "aduwa", "spice", "health", "cooking"],
    image: "https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=400",
    stock: 70,
  },

  // ── Snacks & Beverages ───────────────────────────────────────────────────
  {
    _id: "np_s1",
    name: "Kurkure – Masala Munch 45g",
    category: "Snacks",
    brand: "Kurkure",
    price: 20,
    originalPrice: 20,
    discount: "MRP",
    weight: "45 g",
    rating: 4.5,
    ratingCount: "6.5k",
    tag: "Favourite",
    sales: 6500,
    tags: ["kurkure", "chips", "snack", "masala", "crisps"],
    image: "https://images.unsplash.com/photo-1621447504864-d8686e12698c?w=400",
    stock: 250,
  },
  {
    _id: "np_s2",
    name: "Khoria Chips – Sour Cream 60g",
    category: "Snacks",
    brand: "Khoria",
    price: 50,
    originalPrice: 55,
    discount: "Rs 5 OFF",
    weight: "60 g",
    rating: 4.4,
    ratingCount: "2.1k",
    tag: "Local",
    sales: 2100,
    tags: ["khoria", "chips", "snack", "nepal chips", "crispy"],
    image: "https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=400",
    stock: 150,
  },
  {
    _id: "np_s3",
    name: "Coca-Cola 500ml",
    category: "Beverages",
    brand: "Coca-Cola",
    price: 65,
    originalPrice: 70,
    discount: "Rs 5 OFF",
    weight: "500 ml",
    rating: 4.6,
    ratingCount: "9.0k",
    tag: "Cold",
    sales: 9000,
    tags: ["coke", "cold drink", "soda", "beverage", "cola"],
    image: "https://images.unsplash.com/photo-1554866585-cd94860890b7?w=400",
    stock: 300,
  },
  {
    _id: "np_s4",
    name: "Real Juice – Mango 200ml",
    category: "Beverages",
    brand: "Dabur Real",
    price: 30,
    originalPrice: 35,
    discount: "Rs 5 OFF",
    weight: "200 ml",
    rating: 4.3,
    ratingCount: "3.8k",
    tag: "Kids Fav",
    sales: 4200,
    tags: ["juice", "mango juice", "real juice", "dabur", "drink"],
    image: "https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=400",
    stock: 200,
  },
  {
    _id: "np_s5",
    name: "Himalayan Herbal Tea – Tulsi Ginger 20 bags",
    category: "Beverages",
    brand: "Himalayan Herbal",
    price: 160,
    originalPrice: 180,
    discount: "Rs 20 OFF",
    weight: "20 bags",
    rating: 4.6,
    ratingCount: "2.5k",
    tag: "Herbal",
    sales: 2500,
    tags: ["tulsi tea", "ginger tea", "herbal tea", "himalayan", "health"],
    image: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=400",
    stock: 100,
  },

  // ── Personal Care ────────────────────────────────────────────────────────
  {
    _id: "np_p1",
    name: "Dabur Vatika Coconut Hair Oil 300ml",
    category: "Personal Care",
    brand: "Dabur",
    price: 155,
    originalPrice: 175,
    discount: "Rs 20 OFF",
    weight: "300 ml",
    rating: 4.4,
    ratingCount: "4.2k",
    tag: "Popular",
    sales: 4200,
    tags: ["hair oil", "coconut oil", "vatika", "dabur", "hair care"],
    image: "https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?w=400",
    stock: 80,
  },
  {
    _id: "np_p2",
    name: "Patanjali Neem Tulsi Soap 75g",
    category: "Personal Care",
    brand: "Patanjali",
    price: 30,
    originalPrice: 35,
    discount: "Rs 5 OFF",
    weight: "75 g",
    rating: 4.3,
    ratingCount: "5.8k",
    tag: "Herbal",
    sales: 5800,
    tags: ["soap", "neem", "tulsi", "patanjali", "bath"],
    image: "https://images.unsplash.com/photo-1607006344380-b6775a0824a7?w=400",
    stock: 200,
  },
  {
    _id: "np_p3",
    name: "Colgate Strong Teeth Toothpaste 200g",
    category: "Personal Care",
    brand: "Colgate",
    price: 130,
    originalPrice: 145,
    discount: "Rs 15 OFF",
    weight: "200 g",
    rating: 4.6,
    ratingCount: "7.2k",
    tag: null,
    sales: 7200,
    tags: ["toothpaste", "colgate", "dental", "oral care", "teeth"],
    image: "https://images.unsplash.com/photo-1559056199-5c7176368b29?w=400",
    stock: 150,
  },

  // ── Household ────────────────────────────────────────────────────────────
  {
    _id: "np_h1",
    name: "Dhoop Sticks – Puja Agarbatti (20 sticks)",
    category: "Household",
    brand: "Zed Black",
    price: 40,
    originalPrice: 45,
    discount: "Rs 5 OFF",
    weight: "20 pcs",
    rating: 4.5,
    ratingCount: "2.8k",
    tag: "Puja",
    sales: 4800,
    tags: ["agarbatti", "dhoop", "incense", "puja", "pooja"],
    image: "https://images.unsplash.com/photo-1547571311-6eda4dfc0a12?w=400",
    stock: 200,
  },
  {
    _id: "np_h2",
    name: "Surf Excel Easy Wash Detergent 1kg",
    category: "Household",
    brand: "Surf Excel",
    price: 220,
    originalPrice: 250,
    discount: "Rs 30 OFF",
    weight: "1 kg",
    rating: 4.5,
    ratingCount: "6.1k",
    tag: "Bestseller",
    sales: 6100,
    tags: ["detergent", "surf excel", "washing powder", "laundry", "cleaning"],
    image: "https://images.unsplash.com/photo-1585421514738-01798e348b17?w=400",
    stock: 100,
  },
  {
    _id: "np_h3",
    name: "Vim Dishwash Gel 500ml",
    category: "Household",
    brand: "Vim",
    price: 110,
    originalPrice: 120,
    discount: "Rs 10 OFF",
    weight: "500 ml",
    rating: 4.4,
    ratingCount: "3.3k",
    tag: null,
    sales: 3300,
    tags: ["dishwash", "vim", "dish liquid", "kitchen", "cleaning"],
    image: "https://images.unsplash.com/photo-1563453392212-326f5e854473?w=400",
    stock: 90,
  },

  // ── Baby & Kids ──────────────────────────────────────────────────────────
  {
    _id: "np_k1",
    name: "Mamy Poko Pants – Medium (M) 22 pcs",
    category: "Baby & Kids",
    brand: "MamyPoko",
    price: 620,
    originalPrice: 699,
    discount: "Rs 79 OFF",
    weight: "22 pcs",
    rating: 4.5,
    ratingCount: "8.0k",
    tag: "Bestseller",
    sales: 8000,
    tags: ["diapers", "baby", "mamy poko", "pants", "infant"],
    image: "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=400",
    stock: 80,
  },
  {
    _id: "np_k2",
    name: "Cerelac Wheat – Stage 1 (400g)",
    category: "Baby & Kids",
    brand: "Nestlé",
    price: 430,
    originalPrice: 480,
    discount: "Rs 50 OFF",
    weight: "400 g",
    rating: 4.6,
    ratingCount: "4.2k",
    tag: "Baby",
    sales: 4200,
    tags: ["cerelac", "baby food", "nestle", "infant", "wheat cereal"],
    image: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=400",
    stock: 60,
  },

  // ── Frozen & Ready-to-Eat ─────────────────────────────────────────────────
  {
    _id: "np_f1",
    name: "Frozen Momo – Buff (20 pcs)",
    category: "Frozen Food",
    brand: "Himalayan Chef",
    price: 220,
    originalPrice: 250,
    discount: "Rs 30 OFF",
    weight: "400 g",
    rating: 4.7,
    ratingCount: "5.5k",
    tag: "🔥 Popular",
    sales: 5500,
    tags: ["momo", "buff momo", "frozen", "ready to cook", "snack"],
    image: "https://images.unsplash.com/photo-1496116218417-1a781b1c416c?w=400",
    stock: 80,
  },
  {
    _id: "np_f2",
    name: "Sekuwa Marinade Mix 100g",
    category: "Frozen Food",
    brand: "Local Kitchen",
    price: 90,
    originalPrice: 100,
    discount: "10% OFF",
    weight: "100 g",
    rating: 4.4,
    ratingCount: "600",
    tag: "Local",
    sales: 600,
    tags: ["sekuwa", "barbecue", "marinade", "nepal food", "spice"],
    image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400",
    stock: 50,
  },

  // ── Stationery / Office ───────────────────────────────────────────────────
  {
    _id: "np_st1",
    name: "Rorito Ball Pen – Blue (Pack of 10)",
    category: "Stationery",
    brand: "Rorito",
    price: 60,
    originalPrice: 70,
    discount: "Rs 10 OFF",
    weight: "10 pcs",
    rating: 4.4,
    ratingCount: "7.0k",
    tag: "Bestseller",
    sales: 7000,
    tags: ["pen", "ball pen", "rorito", "writing", "stationery", "office"],
    image: "https://images.unsplash.com/photo-1455390582262-044cdead277a?w=400",
    stock: 300,
  },
];

async function seed() {
  await mongoose.connect(process.env.MONGO_URL);
  console.log("✅  MongoDB connected");

  let created = 0;
  let skipped = 0;

  for (const p of products) {
    const exists = await Product.findById(p._id);
    if (exists) {
      skipped++;
      continue;
    }
    await Product.create(p);
    created++;
    console.log(`  ✔  ${p.name}`);
  }

  console.log(
    `\n📦  Done! ${created} products created, ${skipped} already existed.`,
  );
  await mongoose.disconnect();
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
