/**
 * seed_nepal_products.js
 * Seeds 139 Nepal-context products into MongoDB.
 * Run:  node seed_nepal_products.js
 *
 * Prices are in NPR (Nepalese Rupees).
 * Categories map directly to the app's category system.
 */

import mongoose from "mongoose";
import dotenv from "dotenv";
import { fileURLToPath } from "url";
import path from "path";

dotenv.config({
  path: path.join(path.dirname(fileURLToPath(import.meta.url)), ".env"),
});

const ProductSchema = new mongoose.Schema({
  _id: String,
  name: { type: String, required: true },
  category: { type: String, required: true },
  brand: String,
  description: { type: String, default: "" },
  price: { type: Number, required: true },
  originalPrice: { type: Number, required: true },
  discount: { type: String, default: "MRP" },
  weight: { type: String, default: "" },
  unit: { type: String, default: "" },
  rating: { type: Number, default: 4.0 },
  ratingCount: { type: Number, default: 0 },
  tag: { type: String, default: null },
  sales: { type: Number, default: 0 },
  tags: [String],
  image: { type: String, default: "" },
  stock: { type: Number, default: 50 },
});

const Product = mongoose.model("Product", ProductSchema);

const products = [
  // ── Fresh Vegetables ──────────────────────────────────────────────────────
  {
    _id: "veg_001",
    name: "Tomato (Golbheda) 500g",
    category: "Fruits & Vegetables",
    brand: "Local Farm - Kirtipur",
    description: "Farm-fresh tomatoes sourced daily from Kirtipur farms. Perfect for curries, salads and chutneys.",
    price: 55, originalPrice: 70,
    discount: "21% OFF", weight: "500 g", unit: "500g",
    rating: 4.4, ratingCount: 2100, tag: "Fresh", sales: 2100,
    tags: ["tomato", "golbheda", "fresh", "daily", "vegetable"],
    image: "https://images.unsplash.com/photo-1558818498-28c1e002b655?w=400", stock: 80,
  },
  {
    _id: "veg_002",
    name: "Potato (Aalu) 1kg",
    category: "Fruits & Vegetables",
    brand: "Local Farm - Kavre",
    description: "Premium quality potatoes from Kavre district. Ideal for dal bhat, aloo tarkari and snacks.",
    price: 60, originalPrice: 70,
    discount: "Rs 10 OFF", weight: "1 kg", unit: "1kg",
    rating: 4.3, ratingCount: 3800, tag: "Staple", sales: 3800,
    tags: ["potato", "aalu", "fresh", "daily", "staple"],
    image: "https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=400", stock: 120,
  },
  {
    _id: "veg_003",
    name: "Onion (Pyaz) 500g",
    category: "Fruits & Vegetables",
    brand: "Local Farm",
    description: "Fresh red onions, a staple in every Nepali kitchen for daily cooking.",
    price: 50, originalPrice: 60,
    discount: "Rs 10 OFF", weight: "500 g", unit: "500g",
    rating: 4.2, ratingCount: 2900, tag: null, sales: 2900,
    tags: ["onion", "pyaz", "fresh", "daily", "cooking"],
    image: "https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?w=400", stock: 100,
  },
  {
    _id: "veg_004",
    name: "Cauliflower (Kauli) ~500g",
    category: "Fruits & Vegetables",
    brand: "Local Farm - Bhaktapur",
    description: "Fresh white cauliflower from Bhaktapur farms. Great for gobi tarkari and achar.",
    price: 65, originalPrice: 80,
    discount: "19% OFF", weight: "~500 g", unit: "1 piece",
    rating: 4.3, ratingCount: 1200, tag: "Seasonal", sales: 1200,
    tags: ["cauliflower", "kauli", "fresh", "seasonal", "vegetable"],
    image: "https://images.unsplash.com/photo-1568584711075-3d021a7c3ca3?w=400", stock: 60,
  },
  {
    _id: "veg_005",
    name: "Spinach (Palunggo Saag) 250g",
    category: "Fruits & Vegetables",
    brand: "Local Farm",
    description: "Tender fresh spinach leaves, rich in iron. Perfect for saag and soups.",
    price: 35, originalPrice: 40,
    discount: "Rs 5 OFF", weight: "250 g", unit: "250g bunch",
    rating: 4.4, ratingCount: 900, tag: "Fresh", sales: 1400,
    tags: ["spinach", "palunggo", "saag", "fresh", "leafy", "healthy"],
    image: "https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=400", stock: 50,
  },
  {
    _id: "veg_006",
    name: "Bitter Gourd (Karela) 500g",
    category: "Fruits & Vegetables",
    brand: "Local Farm",
    description: "Nutritious bitter gourd with proven health benefits. Good for blood sugar management.",
    price: 60, originalPrice: 70,
    discount: "Rs 10 OFF", weight: "500 g", unit: "500g",
    rating: 4.1, ratingCount: 600, tag: null, sales: 600,
    tags: ["bitter gourd", "karela", "fresh", "healthy", "vegetable"],
    image: "https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=400", stock: 40,
  },
  {
    _id: "veg_007",
    name: "Green Chilli (Hariyo Khursani) 100g",
    category: "Fruits & Vegetables",
    brand: "Local Farm",
    description: "Fresh green chillies for that authentic spicy Nepali kick. Essential for momos, tarkari and achar.",
    price: 30, originalPrice: 35,
    discount: "Rs 5 OFF", weight: "100 g", unit: "100g",
    rating: 4.3, ratingCount: 1400, tag: "Spicy", sales: 1400,
    tags: ["green chilli", "khursani", "hariyo", "spice", "fresh"],
    image: "https://images.unsplash.com/photo-1601648764658-cf37e8c89b70?w=400", stock: 80,
  },
  {
    _id: "veg_008",
    name: "Garlic (Lasun) 100g",
    category: "Fruits & Vegetables",
    brand: "Local Farm",
    description: "Pungent fresh garlic cloves. A must-have ingredient in Nepali cooking.",
    price: 45, originalPrice: 55,
    discount: "18% OFF", weight: "100 g", unit: "100g",
    rating: 4.5, ratingCount: 2200, tag: "Daily", sales: 2200,
    tags: ["garlic", "lasun", "fresh", "spice", "cooking", "daily"],
    image: "https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=400", stock: 90,
  },
  {
    _id: "veg_009",
    name: "Ginger (Aduwa) 100g",
    category: "Fruits & Vegetables",
    brand: "Local Farm",
    description: "Fresh ginger root for cooking, tea and medicinal use. A staple in every Nepali home.",
    price: 40, originalPrice: 50,
    discount: "20% OFF", weight: "100 g", unit: "100g",
    rating: 4.4, ratingCount: 1800, tag: "Daily", sales: 1800,
    tags: ["ginger", "aduwa", "fresh", "spice", "health", "cooking"],
    image: "https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=400", stock: 80,
  },
  {
    _id: "veg_010",
    name: "Pumpkin (Farsi) 1kg",
    category: "Fruits & Vegetables",
    brand: "Local Farm",
    description: "Sweet and nutritious pumpkin. Great for farsi ko tarkari, soup and sweets.",
    price: 45, originalPrice: 55,
    discount: "18% OFF", weight: "1 kg", unit: "1kg",
    rating: 4.2, ratingCount: 700, tag: null, sales: 700,
    tags: ["pumpkin", "farsi", "fresh", "vegetable", "seasonal"],
    image: "https://images.unsplash.com/photo-1570586437263-ab629fccc818?w=400", stock: 55,
  },
  {
    _id: "veg_011",
    name: "Fenugreek Leaves (Methi Saag) 200g",
    category: "Fruits & Vegetables",
    brand: "Local Farm",
    description: "Fresh fenugreek leaves with a slightly bitter, aromatic flavour. Rich in iron.",
    price: 30, originalPrice: 40,
    discount: "25% OFF", weight: "200 g", unit: "200g",
    rating: 4.1, ratingCount: 500, tag: "Healthy", sales: 500,
    tags: ["methi", "fenugreek", "saag", "leafy", "fresh", "healthy"],
    image: "https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=400", stock: 40,
  },

  // ── Fresh Fruits ──────────────────────────────────────────────────────────
  {
    _id: "frt_001",
    name: "Banana (Kera) 1 Dozen",
    category: "Fruits & Vegetables",
    brand: "Terai Fresh",
    description: "Sweet ripe bananas from Terai. A daily energy source — perfect for breakfast or snacks.",
    price: 90, originalPrice: 110,
    discount: "18% OFF", weight: "1 dozen", unit: "1 dozen",
    rating: 4.5, ratingCount: 3200, tag: "Daily", sales: 3200,
    tags: ["banana", "kera", "fresh", "fruit", "daily", "energy"],
    image: "https://images.unsplash.com/photo-1603833665858-e61d17a86224?w=400", stock: 100,
  },
  {
    _id: "frt_002",
    name: "Apple (Mustang Syau) 500g",
    category: "Fruits & Vegetables",
    brand: "Mustang Apple / Himali Fresh",
    description: "Crisp and sweet apples from Mustang. Enjoy fresh or in juices and desserts.",
    price: 195, originalPrice: 230,
    discount: "15% OFF", weight: "500 g (4–5 pcs)", unit: "500g",
    rating: 4.6, ratingCount: 2800, tag: "Premium", sales: 2800,
    tags: ["apple", "syau", "mustang", "fresh", "fruit", "himalayan"],
    image: "https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=400", stock: 70,
  },
  {
    _id: "frt_003",
    name: "Orange (Suntala) 4 pcs",
    category: "Fruits & Vegetables",
    brand: "Sindhuli Citrus Farm",
    description: "Juicy and tangy oranges from Sindhuli. Rich in Vitamin C and perfect for fresh juice.",
    price: 120, originalPrice: 150,
    discount: "20% OFF", weight: "4 pcs", unit: "4 pcs",
    rating: 4.4, ratingCount: 1600, tag: "Seasonal", sales: 1600,
    tags: ["orange", "suntala", "citrus", "fresh", "fruit", "vitamin c"],
    image: "https://images.unsplash.com/photo-1611080626919-7cf5a9dbab12?w=400", stock: 60,
  },
  {
    _id: "frt_004",
    name: "Papaya (Mewa) ~700g",
    category: "Fruits & Vegetables",
    brand: "Terai Fresh",
    description: "Ripe and sweet papaya from Terai region. Great for breakfast, smoothies and digestion.",
    price: 130, originalPrice: 160,
    discount: "19% OFF", weight: "~700 g", unit: "1 piece",
    rating: 4.3, ratingCount: 980, tag: null, sales: 980,
    tags: ["papaya", "mewa", "fresh", "fruit", "tropical"],
    image: "https://images.unsplash.com/photo-1526318896980-cf78c088247c?w=400", stock: 45,
  },
  {
    _id: "frt_005",
    name: "Guava (Amba) 500g",
    category: "Fruits & Vegetables",
    brand: "Local Farm",
    description: "Sweet and fragrant guavas packed with Vitamin C. Great as a fruit or for chutney.",
    price: 100, originalPrice: 120,
    discount: "17% OFF", weight: "500 g", unit: "500g",
    rating: 4.3, ratingCount: 800, tag: null, sales: 800,
    tags: ["guava", "amba", "fresh", "fruit", "vitamin c"],
    image: "https://images.unsplash.com/photo-1536511132770-e5058c7e8c46?w=400", stock: 50,
  },
  {
    _id: "frt_006",
    name: "Pomegranate (Anar) 1 pc",
    category: "Fruits & Vegetables",
    brand: "Himali Fresh",
    description: "Ruby-red pomegranate with antioxidant-rich seeds. A superfood from the Himalayan foothills.",
    price: 120, originalPrice: 150,
    discount: "20% OFF", weight: "1 pc", unit: "1 piece",
    rating: 4.5, ratingCount: 1100, tag: "Healthy", sales: 1100,
    tags: ["pomegranate", "anar", "fresh", "fruit", "antioxidant", "healthy"],
    image: "https://images.unsplash.com/photo-1606914501449-5a96b6ce24ca?w=400", stock: 40,
  },

  // ── Dairy & Eggs ──────────────────────────────────────────────────────────
  {
    _id: "dry_001",
    name: "Sujal Full Cream Milk 500ml",
    category: "Dairy",
    brand: "Sujal",
    description: "Fresh full cream milk from Sujal Dairy. Pasteurised and homogenised for best quality.",
    price: 65, originalPrice: 70,
    discount: "Rs 5 OFF", weight: "500 ml", unit: "500ml",
    rating: 4.5, ratingCount: 4200, tag: "Daily", sales: 4200,
    tags: ["milk", "full cream", "sujal", "dairy", "daily"],
    image: "https://images.unsplash.com/photo-1563636619-e9143da7973b?w=400", stock: 120,
  },
  {
    _id: "dry_002",
    name: "DDC Toned Milk 500ml",
    category: "Dairy",
    brand: "Dairy Development Corporation",
    description: "Government-certified toned milk from DDC. Trusted quality across Nepal.",
    price: 63, originalPrice: 70,
    discount: "10% OFF", weight: "500 ml", unit: "500ml",
    rating: 4.4, ratingCount: 3500, tag: "Daily", sales: 3500,
    tags: ["milk", "toned", "ddc", "dairy", "daily", "government"],
    image: "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400", stock: 150,
  },
  {
    _id: "dry_003",
    name: "Sujal Dahi (Curd) 400g",
    category: "Dairy",
    brand: "Sujal",
    description: "Creamy and thick curd made from fresh milk. Perfect with dal bhat or as a snack.",
    price: 95, originalPrice: 110,
    discount: "14% OFF", weight: "400 g", unit: "400g",
    rating: 4.4, ratingCount: 2100, tag: "Fresh", sales: 2100,
    tags: ["curd", "dahi", "yogurt", "sujal", "dairy", "fresh"],
    image: "https://images.unsplash.com/photo-1567093322916-5a34e4e9cd64?w=400", stock: 70,
  },
  {
    _id: "dry_004",
    name: "Juju Dhau Style Curd 400g",
    category: "Dairy",
    brand: "Bhaktapur Dairy",
    description: "Rich and creamy curd inspired by the famous Juju Dhau of Bhaktapur. A local delicacy.",
    price: 120, originalPrice: 140,
    discount: "14% OFF", weight: "400 g", unit: "400g",
    rating: 4.7, ratingCount: 1500, tag: "Local Premium", sales: 1500,
    tags: ["juju dhau", "curd", "bhaktapur", "local", "premium", "dairy"],
    image: "https://images.unsplash.com/photo-1571212515416-fef01fc43dfd?w=400", stock: 45,
  },
  {
    _id: "dry_005",
    name: "Sujal Paneer 200g",
    category: "Dairy",
    brand: "Sujal",
    description: "Fresh cottage cheese made from pure cow milk. Perfect for paneer tarkari and sandwiches.",
    price: 160, originalPrice: 185,
    discount: "14% OFF", weight: "200 g", unit: "200g",
    rating: 4.4, ratingCount: 1700, tag: null, sales: 1700,
    tags: ["paneer", "cottage cheese", "sujal", "dairy", "protein"],
    image: "https://images.unsplash.com/photo-1631209121750-a9f656d8dd95?w=400", stock: 55,
  },
  {
    _id: "dry_006",
    name: "Sujal Butter 100g",
    category: "Dairy",
    brand: "Sujal",
    description: "Smooth and creamy table butter. Great for rotis, toast and cooking.",
    price: 130, originalPrice: 150,
    discount: "13% OFF", weight: "100 g", unit: "100g",
    rating: 4.5, ratingCount: 2400, tag: null, sales: 2400,
    tags: ["butter", "sujal", "dairy", "spread", "cooking"],
    image: "https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=400", stock: 80,
  },
  {
    _id: "dry_007",
    name: "Cow Ghee 500ml",
    category: "Dairy",
    brand: "Kheti Food / Local Brand",
    description: "Pure cow ghee prepared using traditional methods. Rich aroma, used for cooking and puja.",
    price: 650, originalPrice: 750,
    discount: "13% OFF", weight: "500 ml", unit: "500ml",
    rating: 4.7, ratingCount: 3200, tag: "Pure", sales: 3200,
    tags: ["ghee", "cow ghee", "gaiko", "pure", "cooking", "puja", "premium"],
    image: "https://images.unsplash.com/photo-1631209121750-a9f656d8dd95?w=400", stock: 60,
  },
  {
    _id: "dry_008",
    name: "Cheese Slices 200g (10 slices)",
    category: "Dairy",
    brand: "Sujal / Amul",
    description: "Mild and creamy processed cheese slices. Perfect for sandwiches and burgers.",
    price: 280, originalPrice: 320,
    discount: "13% OFF", weight: "200 g (10 slices)", unit: "200g",
    rating: 4.3, ratingCount: 1100, tag: null, sales: 1100,
    tags: ["cheese", "slices", "processed", "dairy", "sandwich"],
    image: "https://images.unsplash.com/photo-1552767059-ce182ead6c1b?w=400", stock: 50,
  },
  {
    _id: "dry_009",
    name: "Fresh Eggs (Hen) 6 pcs",
    category: "Dairy",
    brand: "Nepal Poultry / Local Farm",
    description: "Farm-fresh hen eggs. Protein-packed and essential for breakfast, baking and cooking.",
    price: 115, originalPrice: 130,
    discount: "12% OFF", weight: "6 pcs", unit: "6 pcs",
    rating: 4.5, ratingCount: 5100, tag: "Fresh", sales: 5100,
    tags: ["eggs", "hen eggs", "protein", "breakfast", "fresh", "farm"],
    image: "https://images.unsplash.com/photo-1498654200943-1088dd4438ae?w=400", stock: 150,
  },
  {
    _id: "dry_010",
    name: "Sweet Lassi 200ml",
    category: "Dairy",
    brand: "Sujal / DDC",
    description: "Chilled sweet lassi made with fresh curd. A refreshing drink for any time of day.",
    price: 85, originalPrice: 100,
    discount: "15% OFF", weight: "200 ml", unit: "200ml",
    rating: 4.4, ratingCount: 1300, tag: "Refreshing", sales: 1300,
    tags: ["lassi", "sweet lassi", "dairy", "beverage", "curd"],
    image: "https://images.unsplash.com/photo-1571212515416-fef01fc43dfd?w=400", stock: 60,
  },

  // ── Staples & Grains ──────────────────────────────────────────────────────
  {
    _id: "grn_001",
    name: "Basmati Rice 1kg",
    category: "Grocery",
    brand: "RTC / Hulas",
    description: "Aromatic long-grain basmati rice. Perfect for biryani, pulao and special occasions.",
    price: 195, originalPrice: 220,
    discount: "11% OFF", weight: "1 kg", unit: "1kg",
    rating: 4.5, ratingCount: 4500, tag: "Bestseller", sales: 4500,
    tags: ["rice", "basmati", "chaamal", "grain", "staple", "aromatic"],
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400", stock: 120,
  },
  {
    _id: "grn_002",
    name: "Local Rice (Jeera Masino) 1kg",
    category: "Grocery",
    brand: "Hulas / Local",
    description: "Fine-grain local Nepali rice with a natural aroma. The staple of every Nepali dal bhat.",
    price: 130, originalPrice: 150,
    discount: "13% OFF", weight: "1 kg", unit: "1kg",
    rating: 4.4, ratingCount: 3800, tag: "Daily", sales: 3800,
    tags: ["rice", "jeera masino", "local", "nepali", "staple", "chaamal"],
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400", stock: 150,
  },
  {
    _id: "grn_003",
    name: "Chiura (Flattened Rice) 500g",
    category: "Grocery",
    brand: "Hulas / Gyan",
    description: "Traditional beaten rice — a versatile Nepali snack. Great with dahi, tarkari or fried.",
    price: 85, originalPrice: 95,
    discount: "11% OFF", weight: "500 g", unit: "500g",
    rating: 4.4, ratingCount: 2200, tag: "Local", sales: 2200,
    tags: ["chiura", "beaten rice", "local", "traditional", "snack", "nepali"],
    image: "https://images.unsplash.com/photo-1536304929831-ee1ca9d44906?w=400", stock: 100,
  },
  {
    _id: "grn_004",
    name: "Red Lentil (Masoor Dal) 500g",
    category: "Grocery",
    brand: "Hulas",
    description: "Tender red lentils that cook quickly. A staple protein source for dal bhat.",
    price: 120, originalPrice: 140,
    discount: "14% OFF", weight: "500 g", unit: "500g",
    rating: 4.4, ratingCount: 2800, tag: "Protein", sales: 2800,
    tags: ["masoor", "lentil", "red dal", "protein", "staple", "pulse"],
    image: "https://images.unsplash.com/photo-1585090018231-6f0a8085d7b6?w=400", stock: 90,
  },
  {
    _id: "grn_005",
    name: "Black Lentil (Maas Dal) 500g",
    category: "Grocery",
    brand: "Local / Hulas",
    description: "Whole black lentils — the base of authentic Nepali black dal. Rich in protein and iron.",
    price: 130, originalPrice: 155,
    discount: "16% OFF", weight: "500 g", unit: "500g",
    rating: 4.3, ratingCount: 1500, tag: "Traditional", sales: 1500,
    tags: ["maas", "kalo dal", "black lentil", "pulse", "protein", "nepali"],
    image: "https://images.unsplash.com/photo-1585090018231-6f0a8085d7b6?w=400", stock: 80,
  },
  {
    _id: "grn_006",
    name: "Wheat Flour (Atta) 1kg",
    category: "Grocery",
    brand: "Gyan / Hulas",
    description: "Finely milled wheat flour for rotis, puris and chapatis. A kitchen essential.",
    price: 110, originalPrice: 125,
    discount: "12% OFF", weight: "1 kg", unit: "1kg",
    rating: 4.3, ratingCount: 3100, tag: "Staple", sales: 3100,
    tags: ["atta", "wheat flour", "roti", "cooking", "staple"],
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400", stock: 150,
  },
  {
    _id: "grn_007",
    name: "Buckwheat Flour (Fapar Pitho) 500g",
    category: "Grocery",
    brand: "Himalayan Organic",
    description: "100% organic buckwheat flour from the Himalayan region. Gluten-free and nutritious.",
    price: 140, originalPrice: 165,
    discount: "15% OFF", weight: "500 g", unit: "500g",
    rating: 4.5, ratingCount: 780, tag: "Organic", sales: 780,
    tags: ["fapar", "buckwheat", "flour", "organic", "gluten-free", "himalayan"],
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400", stock: 60,
  },

  // ── Instant Noodles & Packaged Food ───────────────────────────────────────
  {
    _id: "nod_001",
    name: "Wai Wai Chicken Noodles (5 pack)",
    category: "Grocery",
    brand: "CG Foods (Wai Wai)",
    description: "Nepal's all-time favourite instant noodles. Eat raw, cook in soup, or dry-fry — always delicious.",
    price: 115, originalPrice: 130,
    discount: "12% OFF", weight: "5 × 75 g", unit: "5 pack",
    rating: 4.8, ratingCount: 12000, tag: "🔥 Bestseller", sales: 12000,
    tags: ["wai wai", "chicken", "noodles", "instant", "bestseller", "nepali"],
    image: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=400", stock: 300,
  },
  {
    _id: "nod_002",
    name: "Wai Wai Veg Noodles 75g",
    category: "Grocery",
    brand: "CG Foods (Wai Wai)",
    description: "Classic vegetarian Wai Wai instant noodles. Ready in 3 minutes.",
    price: 25, originalPrice: 30,
    discount: "17% OFF", weight: "75 g", unit: "75g",
    rating: 4.6, ratingCount: 6500, tag: "Veg", sales: 6500,
    tags: ["wai wai", "veg", "noodles", "instant", "vegetarian", "nepali"],
    image: "https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=400", stock: 200,
  },
  {
    _id: "nod_003",
    name: "Rara Noodles Mutton 70g",
    category: "Grocery",
    brand: "Rara (CG Foods)",
    description: "Rara — Nepal's original mutton-flavour instant noodles. A childhood favourite.",
    price: 30, originalPrice: 35,
    discount: "14% OFF", weight: "70 g", unit: "70g",
    rating: 4.5, ratingCount: 4200, tag: "Classic", sales: 4200,
    tags: ["rara", "mutton", "noodles", "instant", "local", "nepali", "classic"],
    image: "https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=400", stock: 180,
  },
  {
    _id: "nod_004",
    name: "Chowmein Noodles (Dry) 400g",
    category: "Grocery",
    brand: "CG Foods / Pearl",
    description: "Dried chowmein noodles for stir-fry. The base of Kathmandu's street-favourite chowmein.",
    price: 130, originalPrice: 150,
    discount: "13% OFF", weight: "400 g", unit: "400g",
    rating: 4.3, ratingCount: 1900, tag: null, sales: 1900,
    tags: ["chowmein", "noodles", "dry", "stir fry", "packaged"],
    image: "https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=400", stock: 100,
  },
  {
    _id: "nod_005",
    name: "Sel Roti Mix 250g",
    category: "Grocery",
    brand: "Himalayan Homemade",
    description: "Ready-to-cook sel roti mix made from rice flour. Prepare the beloved Nepali ring bread at home.",
    price: 160, originalPrice: 185,
    discount: "14% OFF", weight: "250 g", unit: "250g",
    rating: 4.5, ratingCount: 1100, tag: "Festival", sales: 1100,
    tags: ["sel roti", "rice bread", "festival", "local", "traditional", "ready-to-cook"],
    image: "https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=400", stock: 60,
  },

  // ── Beverages ─────────────────────────────────────────────────────────────
  {
    _id: "bev_001",
    name: "Himalayan Sparkling Water 500ml",
    category: "Beverages",
    brand: "Himalayan (CG)",
    description: "Crisp sparkling water from Himalayan natural springs. Refreshing and hydrating.",
    price: 110, originalPrice: 125,
    discount: "12% OFF", weight: "500 ml", unit: "500ml",
    rating: 4.4, ratingCount: 2100, tag: "Sparkling", sales: 2100,
    tags: ["sparkling water", "himalayan", "beverage", "water", "refreshing"],
    image: "https://images.unsplash.com/photo-1548839140-29a749e1cf4d?w=400", stock: 150,
  },
  {
    _id: "bev_002",
    name: "Coca Cola 500ml",
    category: "Beverages",
    brand: "Coca-Cola Nepal",
    description: "The classic fizzy cola drink. Chilled and refreshing, perfect with any meal.",
    price: 70, originalPrice: 80,
    discount: "13% OFF", weight: "500 ml", unit: "500ml",
    rating: 4.6, ratingCount: 9000, tag: "Cold", sales: 9000,
    tags: ["coke", "cola", "soda", "cold drink", "beverage"],
    image: "https://images.unsplash.com/photo-1554866585-cd94860890b7?w=400", stock: 300,
  },
  {
    _id: "bev_003",
    name: "Red Bull Energy Drink 250ml",
    category: "Beverages",
    brand: "Red Bull Nepal",
    description: "The world's leading energy drink. Gives you wings when you need that extra boost.",
    price: 215, originalPrice: 250,
    discount: "14% OFF", weight: "250 ml", unit: "250ml",
    rating: 4.5, ratingCount: 3800, tag: "Energy", sales: 3800,
    tags: ["red bull", "energy drink", "caffeine", "beverage", "boost"],
    image: "https://images.unsplash.com/photo-1606168094336-48f8b0c89e2d?w=400", stock: 120,
  },
  {
    _id: "bev_004",
    name: "Gorkha Beer 650ml",
    category: "Beverages",
    brand: "Gorkha Brewery",
    description: "Nepal's iconic lager beer brewed at the foothills of the Himalayas. Crisp and smooth.",
    price: 390, originalPrice: 420,
    discount: "7% OFF", weight: "650 ml", unit: "650ml",
    rating: 4.5, ratingCount: 6200, tag: "Local Pride", sales: 6200,
    tags: ["gorkha", "beer", "lager", "local", "nepal", "alcohol"],
    image: "https://images.unsplash.com/photo-1535958636474-b021ee887b13?w=400", stock: 100,
  },
  {
    _id: "bev_005",
    name: "Ilam CTC Tea 500g",
    category: "Beverages",
    brand: "Himalayan Tea / Ilam Tea",
    description: "Premium CTC tea from the lush gardens of Ilam, Nepal's tea capital. Full-bodied flavour.",
    price: 380, originalPrice: 430,
    discount: "12% OFF", weight: "500 g", unit: "500g",
    rating: 4.7, ratingCount: 4100, tag: "Premium Nepali", sales: 4100,
    tags: ["ilam", "ctc", "tea", "nepali", "premium", "chai"],
    image: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400", stock: 100,
  },
  {
    _id: "bev_006",
    name: "Instant Coffee Sachets (10 pack)",
    category: "Beverages",
    brand: "CG / Nescafe",
    description: "Rich and aromatic instant coffee sachets. Ready in seconds — your morning just got easier.",
    price: 135, originalPrice: 155,
    discount: "13% OFF", weight: "10 sachets", unit: "10 sachets",
    rating: 4.3, ratingCount: 2200, tag: null, sales: 2200,
    tags: ["coffee", "instant", "sachet", "morning", "caffeine", "beverage"],
    image: "https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=400", stock: 120,
  },
  {
    _id: "bev_007",
    name: "Masala Tea Premix 10 sachets",
    category: "Beverages",
    brand: "Himalayan",
    description: "Spiced masala tea premix with ginger, cardamom and cinnamon. Authentic Nepali chai taste.",
    price: 120, originalPrice: 140,
    discount: "14% OFF", weight: "10 sachets", unit: "10 sachets",
    rating: 4.4, ratingCount: 1600, tag: "Spiced", sales: 1600,
    tags: ["masala tea", "chai", "spiced", "premix", "ginger", "cardamom"],
    image: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400", stock: 100,
  },
  {
    _id: "bev_008",
    name: "Tuborg Strong Beer 650ml",
    category: "Beverages",
    brand: "Gorkha Brewery",
    description: "Tuborg Strong — bold and refreshing strong beer brewed under licence by Gorkha Brewery.",
    price: 410, originalPrice: 445,
    discount: "8% OFF", weight: "650 ml", unit: "650ml",
    rating: 4.3, ratingCount: 4800, tag: null, sales: 4800,
    tags: ["tuborg", "strong beer", "alcohol", "lager", "gorkha"],
    image: "https://images.unsplash.com/photo-1535958636474-b021ee887b13?w=400", stock: 90,
  },
  {
    _id: "bev_009",
    name: "Fruit Punch Juice 1 litre",
    category: "Beverages",
    brand: "Star / CG",
    description: "Tropical fruit punch juice blend — a mix of mango, guava and citrus flavours.",
    price: 195, originalPrice: 220,
    discount: "11% OFF", weight: "1 litre", unit: "1 litre",
    rating: 4.3, ratingCount: 1400, tag: "Kids Fav", sales: 1400,
    tags: ["juice", "fruit punch", "mango", "tropical", "beverage", "kids"],
    image: "https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=400", stock: 90,
  },

  // ── Meat & Seafood ────────────────────────────────────────────────────────
  {
    _id: "mts_001",
    name: "Fresh Chicken (Skinless) 500g",
    category: "Meat & Seafood",
    brand: "Nepal Poultry / Local",
    description: "Freshly cleaned and skinless broiler chicken. Delivered chilled. For momo, curry and sekuwa.",
    price: 290, originalPrice: 340,
    discount: "15% OFF", weight: "500 g", unit: "500g",
    rating: 4.4, ratingCount: 3200, tag: "Fresh", sales: 3200,
    tags: ["chicken", "fresh", "broiler", "protein", "meat", "skinless"],
    image: "https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=400", stock: 60,
  },
  {
    _id: "mts_002",
    name: "Fresh Mutton / Goat Meat 500g",
    category: "Meat & Seafood",
    brand: "Certified Fresh",
    description: "Premium fresh khasi (goat) meat from certified local butchers. Halal and hygienic.",
    price: 850, originalPrice: 950,
    discount: "11% OFF", weight: "500 g", unit: "500g",
    rating: 4.6, ratingCount: 1800, tag: "Premium", sales: 1800,
    tags: ["mutton", "khasi", "goat", "meat", "fresh", "protein", "premium"],
    image: "https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?w=400", stock: 30,
  },
  {
    _id: "mts_003",
    name: "Rohu Fish 500g",
    category: "Meat & Seafood",
    brand: "Local Fishery",
    description: "Fresh Rohu (rohi maachha) from local fisheries. Cleaned and ready to cook.",
    price: 320, originalPrice: 370,
    discount: "14% OFF", weight: "500 g", unit: "500g",
    rating: 4.3, ratingCount: 900, tag: "Fresh", sales: 900,
    tags: ["rohu", "fish", "maachha", "fresh", "protein", "seafood"],
    image: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=400", stock: 30,
  },
  {
    _id: "mts_004",
    name: "Chicken Momo Filling (Ready) 300g",
    category: "Meat & Seafood",
    brand: "Yummy Kitchen",
    description: "Seasoned chicken momo filling — just wrap in dough and steam. Fresh, spiced, and ready to use.",
    price: 245, originalPrice: 280,
    discount: "13% OFF", weight: "300 g", unit: "300g",
    rating: 4.5, ratingCount: 2200, tag: "Ready-to-Cook", sales: 2200,
    tags: ["momo", "chicken", "filling", "ready-to-cook", "local", "street food"],
    image: "https://images.unsplash.com/photo-1496116218417-1a781b1c416c?w=400", stock: 40,
  },
  {
    _id: "mts_005",
    name: "Buff Meat (Water Buffalo) 500g",
    category: "Meat & Seafood",
    brand: "Certified Fresh",
    description: "Fresh water buffalo meat — popular in Kathmandu Valley for buff momos and sekuwa.",
    price: 480, originalPrice: 540,
    discount: "11% OFF", weight: "500 g", unit: "500g",
    rating: 4.4, ratingCount: 1400, tag: "Local", sales: 1400,
    tags: ["buff", "buffalo", "meat", "fresh", "protein", "local", "momo"],
    image: "https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?w=400", stock: 30,
  },

  // ── Cooking Essentials ────────────────────────────────────────────────────
  {
    _id: "cok_001",
    name: "Mustard Oil (Tori Tel) 1 litre",
    category: "Grocery",
    brand: "Hulas / Dhara / Pearl",
    description: "Pure cold-pressed mustard oil with sharp pungent flavour. The go-to cooking oil of Nepal.",
    price: 340, originalPrice: 380,
    discount: "11% OFF", weight: "1 litre", unit: "1 litre",
    rating: 4.5, ratingCount: 5200, tag: "Popular", sales: 5200,
    tags: ["mustard oil", "tori tel", "sarso tel", "cooking oil", "nepali"],
    image: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400", stock: 100,
  },
  {
    _id: "cok_002",
    name: "Sunflower Oil 1 litre",
    category: "Grocery",
    brand: "Pearl / Fortune",
    description: "Light and healthy sunflower cooking oil. Ideal for daily cooking, frying and baking.",
    price: 310, originalPrice: 360,
    discount: "14% OFF", weight: "1 litre", unit: "1 litre",
    rating: 4.3, ratingCount: 3100, tag: null, sales: 3100,
    tags: ["sunflower oil", "cooking oil", "healthy", "light oil"],
    image: "https://images.unsplash.com/photo-1474987031901-d499c4643e2e?w=400", stock: 90,
  },
  {
    _id: "cok_003",
    name: "Turmeric Powder (Besar) 100g",
    category: "Grocery",
    brand: "Himalayan Spices / Patanjali",
    description: "Pure turmeric powder with high curcumin content. Essential for curries and health.",
    price: 65, originalPrice: 80,
    discount: "19% OFF", weight: "100 g", unit: "100g",
    rating: 4.5, ratingCount: 3800, tag: "Pure", sales: 3800,
    tags: ["turmeric", "besar", "haldi", "spice", "cooking", "health"],
    image: "https://images.unsplash.com/photo-1583917630475-f67e3cc6e4e1?w=400", stock: 150,
  },
  {
    _id: "cok_004",
    name: "Cumin (Jeera) 100g",
    category: "Grocery",
    brand: "Himalayan Spices",
    description: "Whole cumin seeds with earthy warm aroma. A must-have spice for tempering dals.",
    price: 85, originalPrice: 100,
    discount: "15% OFF", weight: "100 g", unit: "100g",
    rating: 4.4, ratingCount: 2400, tag: null, sales: 2400,
    tags: ["cumin", "jeera", "spice", "cooking", "tempering"],
    image: "https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=400", stock: 120,
  },
  {
    _id: "cok_005",
    name: "Red Chilli Powder (Khursani) 100g",
    category: "Grocery",
    brand: "Himalayan Spices",
    description: "Fiery red chilli powder with vibrant colour and heat. Perfect for achar, curry and marinade.",
    price: 75, originalPrice: 90,
    discount: "17% OFF", weight: "100 g", unit: "100g",
    rating: 4.3, ratingCount: 2900, tag: "Spicy", sales: 2900,
    tags: ["chilli powder", "khursani", "red chilli", "spice", "hot", "cooking"],
    image: "https://images.unsplash.com/photo-1583917630475-f67e3cc6e4e1?w=400", stock: 130,
  },
  {
    _id: "cok_006",
    name: "Timur (Nepali Sichuan Pepper) 50g",
    category: "Grocery",
    brand: "Himalayan Herbs / Local",
    description: "Nepal's signature spice — timur (jimbu pepper) with a citrusy, numbing bite. Key to sekuwa and momos.",
    price: 90, originalPrice: 110,
    discount: "18% OFF", weight: "50 g", unit: "50g",
    rating: 4.7, ratingCount: 1900, tag: "Nepali Signature", sales: 1900,
    tags: ["timur", "sichuan pepper", "nepali spice", "local", "sekuwa", "authentic"],
    image: "https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=400", stock: 80,
  },
  {
    _id: "cok_007",
    name: "Iodized Salt 1kg",
    category: "Grocery",
    brand: "Saaj / Hulas",
    description: "Refined iodized salt for daily cooking. Essential for every meal.",
    price: 35, originalPrice: 40,
    discount: "Rs 5 OFF", weight: "1 kg", unit: "1kg",
    rating: 4.3, ratingCount: 4200, tag: "Daily", sales: 4200,
    tags: ["salt", "iodized", "nuwoon", "cooking", "staple", "daily"],
    image: "https://images.unsplash.com/photo-1514668460573-777b66e7d7bb?w=400", stock: 200,
  },
  {
    _id: "cok_008",
    name: "White Sugar 1kg",
    category: "Grocery",
    brand: "Nepal Sugar / Hulas",
    description: "Pure white refined sugar for tea, sweets and cooking.",
    price: 85, originalPrice: 95,
    discount: "11% OFF", weight: "1 kg", unit: "1kg",
    rating: 4.2, ratingCount: 3600, tag: "Staple", sales: 3600,
    tags: ["sugar", "chini", "sweet", "staple", "cooking", "daily"],
    image: "https://images.unsplash.com/photo-1514668460573-777b66e7d7bb?w=400", stock: 180,
  },
  {
    _id: "cok_009",
    name: "Tomato Ketchup 500g",
    category: "Grocery",
    brand: "Golchi / Heinz",
    description: "Sweet and tangy tomato ketchup. A universal condiment for momos, snacks and meals.",
    price: 165, originalPrice: 190,
    discount: "13% OFF", weight: "500 g", unit: "500g",
    rating: 4.4, ratingCount: 3200, tag: "Popular", sales: 3200,
    tags: ["ketchup", "tomato sauce", "golchi", "condiment", "momo"],
    image: "https://images.unsplash.com/photo-1558818498-28c1e002b655?w=400", stock: 90,
  },
  {
    _id: "cok_010",
    name: "Soybean Sauce (Soyabari) 200ml",
    category: "Grocery",
    brand: "CG / Golchi",
    description: "Dark soy sauce for stir-fries, chowmein and dips. Adds umami depth to any dish.",
    price: 130, originalPrice: 150,
    discount: "13% OFF", weight: "200 ml", unit: "200ml",
    rating: 4.3, ratingCount: 1400, tag: null, sales: 1400,
    tags: ["soy sauce", "soyabari", "chowmein", "cooking", "condiment"],
    image: "https://images.unsplash.com/photo-1613844237701-8f3664fc2eff?w=400", stock: 70,
  },

  // ── Snacks & Namkeen ──────────────────────────────────────────────────────
  {
    _id: "snk_001",
    name: "Kurkure Masala Munch 45g",
    category: "Snacks",
    brand: "PepsiCo Nepal",
    description: "Crispy corn puffs with spicy masala seasoning. Nepal's favourite munchies.",
    price: 35, originalPrice: 40,
    discount: "13% OFF", weight: "45 g", unit: "45g",
    rating: 4.5, ratingCount: 8200, tag: "Favourite", sales: 8200,
    tags: ["kurkure", "masala", "snack", "chips", "puffs", "spicy"],
    image: "https://images.unsplash.com/photo-1621447504864-d8686e12698c?w=400", stock: 250,
  },
  {
    _id: "snk_002",
    name: "Lays Classic Salted 26g",
    category: "Snacks",
    brand: "PepsiCo Nepal",
    description: "Light and crunchy potato chips with classic salt seasoning. Irresistible any time.",
    price: 30, originalPrice: 35,
    discount: "14% OFF", weight: "26 g", unit: "26g",
    rating: 4.5, ratingCount: 7400, tag: "Classic", sales: 7400,
    tags: ["lays", "chips", "classic", "salted", "potato", "snack"],
    image: "https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=400", stock: 250,
  },
  {
    _id: "snk_003",
    name: "Bhuja Mix (Nepali Namkeen) 200g",
    category: "Snacks",
    brand: "Gyan / Local Brand",
    description: "Traditional Nepali bhuja mix with beaten rice, peanuts and spiced puffed corn. A heritage snack.",
    price: 85, originalPrice: 100,
    discount: "15% OFF", weight: "200 g", unit: "200g",
    rating: 4.5, ratingCount: 3100, tag: "Traditional", sales: 3100,
    tags: ["bhuja", "namkeen", "local", "traditional", "peanuts", "snack", "nepali"],
    image: "https://images.unsplash.com/photo-1621447504864-d8686e12698c?w=400", stock: 120,
  },
  {
    _id: "snk_004",
    name: "Dairy Milk Chocolate Bar 40g",
    category: "Snacks",
    brand: "Cadbury",
    description: "Classic Cadbury Dairy Milk — smooth milk chocolate loved by all ages.",
    price: 110, originalPrice: 130,
    discount: "15% OFF", weight: "40 g", unit: "40g",
    rating: 4.7, ratingCount: 6800, tag: "Sweet", sales: 6800,
    tags: ["dairy milk", "chocolate", "cadbury", "sweet", "snack", "gift"],
    image: "https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=400", stock: 180,
  },
  {
    _id: "snk_005",
    name: "Kwiks Ice Cream Bar 80ml",
    category: "Snacks",
    brand: "CG Beverages / Kwiks",
    description: "Creamy Kwiks ice cream bar — Nepal's beloved chilled treat. Available in multiple flavours.",
    price: 65, originalPrice: 75,
    discount: "13% OFF", weight: "80 ml", unit: "1 pc",
    rating: 4.4, ratingCount: 3500, tag: "Chilled", sales: 3500,
    tags: ["kwiks", "ice cream", "bar", "chilled", "cg", "sweet", "nepali"],
    image: "https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?w=400", stock: 100,
  },
  {
    _id: "snk_006",
    name: "Popcorn Butter Flavour 80g",
    category: "Snacks",
    brand: "Act II / Local",
    description: "Buttery and light microwave popcorn. Perfect for movie nights and evening snacks.",
    price: 85, originalPrice: 100,
    discount: "15% OFF", weight: "80 g", unit: "80g",
    rating: 4.3, ratingCount: 1800, tag: null, sales: 1800,
    tags: ["popcorn", "butter", "snack", "movie", "microwave"],
    image: "https://images.unsplash.com/photo-1585647347483-22b66260dfff?w=400", stock: 120,
  },
  {
    _id: "snk_007",
    name: "Monaco Biscuit 200g",
    category: "Snacks",
    brand: "Royal / Parle",
    description: "Crispy cream cracker biscuits — light, salted and perfect with tea or as a standalone snack.",
    price: 95, originalPrice: 110,
    discount: "14% OFF", weight: "200 g", unit: "200g",
    rating: 4.3, ratingCount: 2600, tag: null, sales: 2600,
    tags: ["biscuit", "monaco", "cracker", "snack", "tea time"],
    image: "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=400", stock: 150,
  },

  // ── Personal Care ─────────────────────────────────────────────────────────
  {
    _id: "prs_001",
    name: "Sunsilk Shampoo 180ml",
    category: "Personal Care",
    brand: "Unilever Nepal",
    description: "Nourishing shampoo for smooth and manageable hair. Anti-hair fall formula.",
    price: 230, originalPrice: 265,
    discount: "13% OFF", weight: "180 ml", unit: "180ml",
    rating: 4.4, ratingCount: 5200, tag: "Popular", sales: 5200,
    tags: ["shampoo", "sunsilk", "hair care", "anti hair fall", "unilever"],
    image: "https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?w=400", stock: 90,
  },
  {
    _id: "prs_002",
    name: "Dabur Amla Hair Oil 200ml",
    category: "Personal Care",
    brand: "Dabur",
    description: "Amla-enriched hair oil for strong, lustrous hair. Reduces hair fall and promotes growth.",
    price: 280, originalPrice: 320,
    discount: "13% OFF", weight: "200 ml", unit: "200ml",
    rating: 4.5, ratingCount: 6100, tag: "Trusted", sales: 6100,
    tags: ["hair oil", "amla", "dabur", "hair care", "growth", "ayurvedic"],
    image: "https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?w=400", stock: 80,
  },
  {
    _id: "prs_003",
    name: "Patanjali Dant Kanti Toothpaste 100g",
    category: "Personal Care",
    brand: "Patanjali Nepal",
    description: "Ayurvedic toothpaste with neem, clove and mint. Strengthens teeth and freshens breath.",
    price: 100, originalPrice: 120,
    discount: "17% OFF", weight: "100 g", unit: "100g",
    rating: 4.4, ratingCount: 7800, tag: "Ayurvedic", sales: 7800,
    tags: ["toothpaste", "patanjali", "ayurvedic", "neem", "oral care"],
    image: "https://images.unsplash.com/photo-1559056199-5c7176368b29?w=400", stock: 150,
  },
  {
    _id: "prs_004",
    name: "Colgate Strong Teeth Toothpaste 200g",
    category: "Personal Care",
    brand: "Colgate-Palmolive Nepal",
    description: "Maximum strength cavity protection toothpaste with fluoride. Clinically proven formula.",
    price: 215, originalPrice: 250,
    discount: "14% OFF", weight: "200 g", unit: "200g",
    rating: 4.6, ratingCount: 9200, tag: "Bestseller", sales: 9200,
    tags: ["toothpaste", "colgate", "cavity protection", "fluoride", "oral care"],
    image: "https://images.unsplash.com/photo-1559056199-5c7176368b29?w=400", stock: 180,
  },
  {
    _id: "prs_005",
    name: "Lux Beauty Soap 80g",
    category: "Personal Care",
    brand: "Unilever Nepal",
    description: "Fragrant beauty soap with a creamy lather. Leaves skin smooth, soft and refreshed.",
    price: 75, originalPrice: 90,
    discount: "17% OFF", weight: "80 g", unit: "80g",
    rating: 4.4, ratingCount: 5800, tag: null, sales: 5800,
    tags: ["soap", "lux", "beauty", "bath", "fragrant", "unilever"],
    image: "https://images.unsplash.com/photo-1607006344380-b6775a0824a7?w=400", stock: 200,
  },
  {
    _id: "prs_006",
    name: "Nivea Moisturizing Cream 50ml",
    category: "Personal Care",
    brand: "Nivea Nepal",
    description: "Intense moisturizing cream that repairs dry skin. The iconic blue tin with 24-hour hydration.",
    price: 240, originalPrice: 280,
    discount: "14% OFF", weight: "50 ml", unit: "50ml",
    rating: 4.6, ratingCount: 5400, tag: "Trusted", sales: 5400,
    tags: ["nivea", "moisturizer", "cream", "skin care", "hydration", "dry skin"],
    image: "https://images.unsplash.com/photo-1607006344380-b6775a0824a7?w=400", stock: 80,
  },
  {
    _id: "prs_007",
    name: "Whisper Ultra Pads 6 pcs",
    category: "Personal Care",
    brand: "P&G",
    description: "Ultra-thin sanitary pads with advanced leakage protection. Keeps you comfortable all day.",
    price: 180, originalPrice: 210,
    discount: "14% OFF", weight: "6 pcs", unit: "6 pcs",
    rating: 4.5, ratingCount: 4200, tag: null, sales: 4200,
    tags: ["whisper", "sanitary pads", "feminine hygiene", "ultra thin", "personal care"],
    image: "https://images.unsplash.com/photo-1607006344380-b6775a0824a7?w=400", stock: 120,
  },
  {
    _id: "prs_008",
    name: "Axe Deodorant Spray 150ml",
    category: "Personal Care",
    brand: "Axe / Rexona",
    description: "Long-lasting deodorant spray for men. 48-hour freshness and confidence.",
    price: 395, originalPrice: 450,
    discount: "12% OFF", weight: "150 ml", unit: "150ml",
    rating: 4.4, ratingCount: 3600, tag: null, sales: 3600,
    tags: ["deodorant", "axe", "men", "freshness", "spray", "personal care"],
    image: "https://images.unsplash.com/photo-1557821552-17105176677c?w=400", stock: 80,
  },

  // ── Household Cleaning ────────────────────────────────────────────────────
  {
    _id: "hld_001",
    name: "Surf Excel Washing Powder 1kg",
    category: "Household",
    brand: "Unilever Nepal",
    description: "Powerful stain-removing washing powder. Works on tough stains in just one wash.",
    price: 335, originalPrice: 380,
    discount: "12% OFF", weight: "1 kg", unit: "1kg",
    rating: 4.5, ratingCount: 7200, tag: "Bestseller", sales: 7200,
    tags: ["surf excel", "detergent", "washing powder", "laundry", "cleaning", "stain"],
    image: "https://images.unsplash.com/photo-1585421514738-01798e348b17?w=400", stock: 100,
  },
  {
    _id: "hld_002",
    name: "Vim Dishwash Bar 200g",
    category: "Household",
    brand: "Unilever Nepal",
    description: "Powerful dishwash bar that cuts through grease and leaves utensils sparkling clean.",
    price: 90, originalPrice: 105,
    discount: "14% OFF", weight: "200 g", unit: "200g",
    rating: 4.4, ratingCount: 4100, tag: null, sales: 4100,
    tags: ["vim", "dishwash", "bar", "kitchen", "cleaning", "utensils"],
    image: "https://images.unsplash.com/photo-1563453392212-326f5e854473?w=400", stock: 150,
  },
  {
    _id: "hld_003",
    name: "Harpic Toilet Cleaner 500ml",
    category: "Household",
    brand: "Reckitt Benckiser",
    description: "Powerful toilet bowl cleaner that kills 99.9% germs. Removes tough stains and limescale.",
    price: 290, originalPrice: 340,
    discount: "15% OFF", weight: "500 ml", unit: "500ml",
    rating: 4.4, ratingCount: 3800, tag: null, sales: 3800,
    tags: ["harpic", "toilet cleaner", "disinfectant", "cleaning", "bathroom"],
    image: "https://images.unsplash.com/photo-1563453392212-326f5e854473?w=400", stock: 80,
  },
  {
    _id: "hld_004",
    name: "Lizol Floor Cleaner 500ml",
    category: "Household",
    brand: "Reckitt Benckiser",
    description: "Disinfectant floor cleaner that kills germs and leaves floors shining with a fresh fragrance.",
    price: 310, originalPrice: 360,
    discount: "14% OFF", weight: "500 ml", unit: "500ml",
    rating: 4.4, ratingCount: 3200, tag: null, sales: 3200,
    tags: ["lizol", "floor cleaner", "disinfectant", "cleaning", "fragrance"],
    image: "https://images.unsplash.com/photo-1563453392212-326f5e854473?w=400", stock: 70,
  },
  {
    _id: "hld_005",
    name: "Dettol Antiseptic Liquid 250ml",
    category: "Household",
    brand: "Reckitt Benckiser",
    description: "Trusted antiseptic liquid for wound care, hygiene and household disinfection.",
    price: 310, originalPrice: 360,
    discount: "14% OFF", weight: "250 ml", unit: "250ml",
    rating: 4.6, ratingCount: 5500, tag: "Trusted", sales: 5500,
    tags: ["dettol", "antiseptic", "health", "disinfectant", "wound care"],
    image: "https://images.unsplash.com/photo-1585421514738-01798e348b17?w=400", stock: 90,
  },
  {
    _id: "hld_006",
    name: "Goodnight Mosquito Coil (10 coils)",
    category: "Household",
    brand: "Goodnight / Mortein",
    description: "Long-burning mosquito coils for effective pest control. Protects for up to 8 hours.",
    price: 85, originalPrice: 100,
    discount: "15% OFF", weight: "10 coils", unit: "10 coils",
    rating: 4.3, ratingCount: 2800, tag: null, sales: 2800,
    tags: ["mosquito coil", "goodnight", "pest control", "household", "protection"],
    image: "https://images.unsplash.com/photo-1547571311-6eda4dfc0a12?w=400", stock: 130,
  },
  {
    _id: "hld_007",
    name: "Plastic Garbage Bags 30 pcs",
    category: "Household",
    brand: "Local Brand",
    description: "Strong medium-size garbage bags for daily trash disposal. Leak-proof and durable.",
    price: 110, originalPrice: 130,
    discount: "15% OFF", weight: "30 pcs", unit: "30 pcs",
    rating: 4.2, ratingCount: 1900, tag: null, sales: 1900,
    tags: ["garbage bags", "trash", "disposal", "household", "cleaning"],
    image: "https://images.unsplash.com/photo-1563453392212-326f5e854473?w=400", stock: 120,
  },

  // ── Baby Care ─────────────────────────────────────────────────────────────
  {
    _id: "bby_001",
    name: "Pampers Baby Dry Diapers Small (20 pcs)",
    category: "Baby & Kids",
    brand: "Pampers (P&G)",
    description: "Ultra-absorbent diapers for babies up to 8 kg. Keeps baby dry for up to 12 hours.",
    price: 750, originalPrice: 870,
    discount: "14% OFF", weight: "20 pcs", unit: "20 pcs",
    rating: 4.6, ratingCount: 5200, tag: "Bestseller", sales: 5200,
    tags: ["pampers", "diapers", "baby", "dry", "newborn", "infant"],
    image: "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=400", stock: 70,
  },
  {
    _id: "bby_002",
    name: "Huggies Wonder Pants Medium (20 pcs)",
    category: "Baby & Kids",
    brand: "Huggies (Kimberly-Clark)",
    description: "Easy pull-up pants diapers for active babies 7–12 kg. 360° stretch for comfortable fit.",
    price: 780, originalPrice: 900,
    discount: "13% OFF", weight: "20 pcs", unit: "20 pcs",
    rating: 4.5, ratingCount: 4800, tag: "Popular", sales: 4800,
    tags: ["huggies", "diapers", "baby", "pull-up", "pants", "medium"],
    image: "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=400", stock: 65,
  },
  {
    _id: "bby_003",
    name: "Johnson's Baby Shampoo 200ml",
    category: "Baby & Kids",
    brand: "Johnson & Johnson",
    description: "Gentle tear-free baby shampoo with No More Tears formula. Safe for sensitive baby eyes.",
    price: 390, originalPrice: 445,
    discount: "12% OFF", weight: "200 ml", unit: "200ml",
    rating: 4.7, ratingCount: 6100, tag: "Gentle", sales: 6100,
    tags: ["baby shampoo", "johnson", "tear-free", "gentle", "baby care"],
    image: "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=400", stock: 80,
  },
  {
    _id: "bby_004",
    name: "Cerelac Wheat + Milk 300g",
    category: "Baby & Kids",
    brand: "Nestlé Nepal",
    description: "Nutrient-rich wheat cereal with milk for babies from 6 months. Fortified with iron and vitamins.",
    price: 520, originalPrice: 590,
    discount: "12% OFF", weight: "300 g", unit: "300g",
    rating: 4.6, ratingCount: 4400, tag: "Nutritious", sales: 4400,
    tags: ["cerelac", "baby food", "nestle", "infant", "wheat", "milk", "nutrition"],
    image: "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=400", stock: 60,
  },

  // ── Health & Wellness ─────────────────────────────────────────────────────
  {
    _id: "hlw_001",
    name: "ORS Electrolyte Sachets 5 pcs",
    category: "Health & Wellness",
    brand: "Jeevan Jal / WHO ORS",
    description: "WHO-standard oral rehydration salts. Essential for dehydration from diarrhoea or heat.",
    price: 60, originalPrice: 70,
    discount: "14% OFF", weight: "5 sachets", unit: "5 sachets",
    rating: 4.6, ratingCount: 2400, tag: "Essential", sales: 2400,
    tags: ["ors", "electrolyte", "rehydration", "health", "hydration", "medical"],
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400", stock: 150,
  },
  {
    _id: "hlw_002",
    name: "Himalayan Raw Honey 250g",
    category: "Health & Wellness",
    brand: "Himalayan Honey Nepal",
    description: "Pure raw honey collected from wild Himalayan bee colonies. Unprocessed and full of nutrients.",
    price: 480, originalPrice: 550,
    discount: "13% OFF", weight: "250 g", unit: "250g",
    rating: 4.7, ratingCount: 3600, tag: "Pure Natural", sales: 3600,
    tags: ["honey", "himalayan", "raw", "natural", "health", "immune", "maha"],
    image: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=400", stock: 60,
  },
  {
    _id: "hlw_003",
    name: "Chyawanprash 250g",
    category: "Health & Wellness",
    brand: "Dabur / Patanjali",
    description: "Traditional ayurvedic immunity booster with 40+ herbs. Strengthens body and mind year-round.",
    price: 320, originalPrice: 370,
    discount: "14% OFF", weight: "250 g", unit: "250g",
    rating: 4.5, ratingCount: 5800, tag: "Immunity", sales: 5800,
    tags: ["chyawanprash", "ayurvedic", "immunity", "health", "dabur", "herbal"],
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400", stock: 80,
  },
  {
    _id: "hlw_004",
    name: "Tulsi Drops 20ml",
    category: "Health & Wellness",
    brand: "Dabur / Patanjali",
    description: "Concentrated tulsi (holy basil) drops for immunity. Add to water or tea for daily wellness.",
    price: 130, originalPrice: 155,
    discount: "16% OFF", weight: "20 ml", unit: "20ml",
    rating: 4.4, ratingCount: 2100, tag: "Herbal", sales: 2100,
    tags: ["tulsi", "drops", "immunity", "ayurvedic", "herbal", "health"],
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400", stock: 100,
  },
  {
    _id: "hlw_005",
    name: "Vitamin C Tablets 500mg (10 tabs)",
    category: "Health & Wellness",
    brand: "CiplaNepal / generic",
    description: "Vitamin C effervescent tablets for immune support, skin health and antioxidant protection.",
    price: 120, originalPrice: 140,
    discount: "14% OFF", weight: "10 tabs", unit: "10 tabs",
    rating: 4.4, ratingCount: 1900, tag: null, sales: 1900,
    tags: ["vitamin c", "supplement", "immune", "health", "tablet", "cipla"],
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400", stock: 120,
  },
  {
    _id: "hlw_006",
    name: "Bandaid Adhesive Strips 10 pcs",
    category: "Health & Wellness",
    brand: "Band-Aid / Dettol",
    description: "Flexible adhesive bandage strips for minor cuts and wounds. Quick and easy first aid.",
    price: 70, originalPrice: 85,
    discount: "18% OFF", weight: "10 strips", unit: "10 strips",
    rating: 4.5, ratingCount: 2800, tag: "First Aid", sales: 2800,
    tags: ["bandaid", "plaster", "first aid", "wound", "health"],
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400", stock: 150,
  },

  // ── Bakery & Bread ────────────────────────────────────────────────────────
  {
    _id: "bkr_001",
    name: "White Sandwich Bread 400g (20 slices)",
    category: "Bakery",
    brand: "Modern / Nepal Bakery",
    description: "Soft and fresh white sandwich bread sliced for convenience. Perfect for toast and sandwiches.",
    price: 105, originalPrice: 120,
    discount: "13% OFF", weight: "400 g (20 slices)", unit: "400g",
    rating: 4.3, ratingCount: 3200, tag: "Fresh", sales: 3200,
    tags: ["bread", "white bread", "sandwich", "toast", "sliced", "breakfast"],
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400", stock: 80,
  },
  {
    _id: "bkr_002",
    name: "Whole Wheat Bread 400g",
    category: "Bakery",
    brand: "Modern / Harvest Gold",
    description: "Nutritious whole wheat bread with fibre and goodness. A healthier daily bread choice.",
    price: 135, originalPrice: 155,
    discount: "13% OFF", weight: "400 g", unit: "400g",
    rating: 4.4, ratingCount: 2100, tag: "Healthy", sales: 2100,
    tags: ["whole wheat", "bread", "healthy", "fibre", "brown bread"],
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400", stock: 70,
  },
  {
    _id: "bkr_003",
    name: "Samosa 2 pcs",
    category: "Bakery",
    brand: "Local Bakery / Fresho",
    description: "Crispy deep-fried samosas stuffed with spiced potato filling. A beloved Nepali snack.",
    price: 60, originalPrice: 70,
    discount: "14% OFF", weight: "2 pcs", unit: "2 pcs",
    rating: 4.5, ratingCount: 4100, tag: "Snack", sales: 4100,
    tags: ["samosa", "snack", "fried", "potato", "local", "bakery"],
    image: "https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=400", stock: 60,
  },
  {
    _id: "bkr_004",
    name: "Chocolate Muffin 1 pc",
    category: "Bakery",
    brand: "Bakery Fresh / Yellow Bakery",
    description: "Freshly baked chocolate muffin with a rich moist crumb. Baked daily from local bakeries.",
    price: 95, originalPrice: 110,
    discount: "14% OFF", weight: "1 pc", unit: "1 pc",
    rating: 4.4, ratingCount: 1600, tag: "Fresh", sales: 1600,
    tags: ["muffin", "chocolate", "bakery", "sweet", "fresh", "cake"],
    image: "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=400", stock: 40,
  },

  // ── Stationery & Office ───────────────────────────────────────────────────
  {
    _id: "stn_001",
    name: "Ballpoint Pen Blue 10 pack",
    category: "Stationery",
    brand: "Reynolds / Cello",
    description: "Smooth-writing blue ballpoint pens. Essential for school, office and everyday writing.",
    price: 90, originalPrice: 110,
    discount: "18% OFF", weight: "10 pcs", unit: "10 pcs",
    rating: 4.4, ratingCount: 8200, tag: "Bestseller", sales: 8200,
    tags: ["pen", "ballpoint", "blue", "stationery", "writing", "office"],
    image: "https://images.unsplash.com/photo-1455390582262-044cdead277a?w=400", stock: 300,
  },
  {
    _id: "stn_002",
    name: "A4 Notebook 120 pages",
    category: "Stationery",
    brand: "Janaki / Local",
    description: "Ruled A4 notebook with 120 pages. Ideal for school notes, journaling and work.",
    price: 120, originalPrice: 145,
    discount: "17% OFF", weight: "120 pages", unit: "1 pc",
    rating: 4.3, ratingCount: 2900, tag: null, sales: 2900,
    tags: ["notebook", "a4", "ruled", "stationery", "school", "study"],
    image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400", stock: 150,
  },
  {
    _id: "stn_003",
    name: "AA Batteries 4 pcs",
    category: "Stationery",
    brand: "Eveready / Duracell",
    description: "Long-lasting AA batteries for remotes, clocks, torches and everyday devices.",
    price: 160, originalPrice: 190,
    discount: "16% OFF", weight: "4 pcs", unit: "4 pcs",
    rating: 4.4, ratingCount: 3600, tag: null, sales: 3600,
    tags: ["batteries", "aa", "eveready", "duracell", "electronics"],
    image: "https://images.unsplash.com/photo-1610270350897-5df88a9aa3a1?w=400", stock: 200,
  },

  // ── Mobile & Electronics ──────────────────────────────────────────────────
  {
    _id: "elc_001",
    name: "Type-C Charging Cable 1m",
    category: "Electronics",
    brand: "Anker / Local",
    description: "Fast-charging Type-C cable compatible with Android phones, laptops and tablets.",
    price: 295, originalPrice: 350,
    discount: "16% OFF", weight: "1 m", unit: "1 pc",
    rating: 4.4, ratingCount: 3800, tag: "Fast Charge", sales: 3800,
    tags: ["usb-c", "type-c", "cable", "charging", "android", "electronics"],
    image: "https://images.unsplash.com/photo-1610270350897-5df88a9aa3a1?w=400", stock: 100,
  },
  {
    _id: "elc_002",
    name: "5W USB Charger Adapter",
    category: "Electronics",
    brand: "Syska / Local",
    description: "Compact USB wall adapter with broad input voltage support. Works with Nepal's 230V outlets.",
    price: 350, originalPrice: 420,
    discount: "17% OFF", weight: "1 pc", unit: "1 pc",
    rating: 4.3, ratingCount: 2100, tag: null, sales: 2100,
    tags: ["charger", "usb", "adapter", "wall charger", "mobile", "electronics"],
    image: "https://images.unsplash.com/photo-1610270350897-5df88a9aa3a1?w=400", stock: 80,
  },
  {
    _id: "elc_003",
    name: "Wired Earphones 3.5mm",
    category: "Electronics",
    brand: "Boat / Local",
    description: "Comfortable in-ear earphones with enhanced bass and clear vocals. Universal 3.5mm jack.",
    price: 380, originalPrice: 450,
    discount: "16% OFF", weight: "1 pc", unit: "1 pc",
    rating: 4.3, ratingCount: 2600, tag: null, sales: 2600,
    tags: ["earphones", "wired", "3.5mm", "audio", "music", "electronics"],
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400", stock: 70,
  },

  // ── Puja & Festival Items ─────────────────────────────────────────────────
  {
    _id: "pja_001",
    name: "Agarbatti Incense Sticks 20 pcs",
    category: "Puja & Festival",
    brand: "Cycle / Patanjali",
    description: "Fragrant incense sticks for daily puja, meditation and home ambience. Long-burning formula.",
    price: 45, originalPrice: 55,
    discount: "18% OFF", weight: "20 sticks", unit: "20 sticks",
    rating: 4.5, ratingCount: 5600, tag: "Puja", sales: 5600,
    tags: ["agarbatti", "incense", "puja", "festival", "fragrance", "worship"],
    image: "https://images.unsplash.com/photo-1547571311-6eda4dfc0a12?w=400", stock: 250,
  },
  {
    _id: "pja_002",
    name: "Clay Oil Lamp (Diyo) 5 pcs",
    category: "Puja & Festival",
    brand: "Local Pottery",
    description: "Traditional hand-made clay diyo (oil lamp) for puja and Tihar. The light of devotion.",
    price: 60, originalPrice: 75,
    discount: "20% OFF", weight: "5 pcs", unit: "5 pcs",
    rating: 4.6, ratingCount: 3200, tag: "Traditional", sales: 3200,
    tags: ["diyo", "clay lamp", "oil lamp", "puja", "tihar", "festival", "traditional"],
    image: "https://images.unsplash.com/photo-1604881988758-f76ad2f7aac1?w=400", stock: 150,
  },
  {
    _id: "pja_003",
    name: "Tika Set (Sindur, Abir, Rice)",
    category: "Puja & Festival",
    brand: "Local",
    description: "Complete dashain tika set with vermillion (sindur), coloured powder (abir) and rice. Festival-ready.",
    price: 95, originalPrice: 115,
    discount: "17% OFF", weight: "1 set", unit: "1 set",
    rating: 4.6, ratingCount: 2800, tag: "Festival", sales: 2800,
    tags: ["tika", "sindur", "abir", "dashain", "puja", "festival", "nepali"],
    image: "https://images.unsplash.com/photo-1604881988758-f76ad2f7aac1?w=400", stock: 100,
  },
  {
    _id: "pja_004",
    name: "Marigold Garland (Sayapatri) 1 garland",
    category: "Puja & Festival",
    brand: "Local Farm",
    description: "Fresh marigold flower garland for Tihar, puja and celebrations. Vibrant orange-yellow colour.",
    price: 65, originalPrice: 80,
    discount: "19% OFF", weight: "1 garland", unit: "1 garland",
    rating: 4.5, ratingCount: 1900, tag: "Fresh", sales: 1900,
    tags: ["marigold", "sayapatri", "garland", "tihar", "puja", "flowers", "festival"],
    image: "https://images.unsplash.com/photo-1592503254549-d83d24a4dfab?w=400", stock: 80,
  },
  {
    _id: "pja_005",
    name: "Camphor (Kapur) 25g",
    category: "Puja & Festival",
    brand: "Patanjali / Local",
    description: "Pure camphor for puja, aarti and natural moth-repelling. Strong and long-lasting fragrance.",
    price: 65, originalPrice: 80,
    discount: "19% OFF", weight: "25 g", unit: "25g",
    rating: 4.5, ratingCount: 2400, tag: "Puja", sales: 2400,
    tags: ["camphor", "kapur", "puja", "aarti", "fragrance", "worship"],
    image: "https://images.unsplash.com/photo-1547571311-6eda4dfc0a12?w=400", stock: 120,
  },

  // ── Legacy products kept for backwards compatibility ──────────────────────
  {
    _id: "np_f1",
    name: "Frozen Buff Momo 20 pcs",
    category: "Frozen Food",
    brand: "Himalayan Chef",
    description: "Ready-to-steam frozen buff momos seasoned with timur and ginger. Nepal's all-time street food.",
    price: 220, originalPrice: 250,
    discount: "12% OFF", weight: "400 g", unit: "400g",
    rating: 4.7, ratingCount: 5500, tag: "🔥 Popular", sales: 5500,
    tags: ["momo", "buff", "frozen", "ready to cook", "street food", "nepali"],
    image: "https://images.unsplash.com/photo-1496116218417-1a781b1c416c?w=400", stock: 80,
  },
  {
    _id: "np_h1",
    name: "Dhoop Agarbatti Puja Sticks 20 pcs",
    category: "Household",
    brand: "Zed Black",
    description: "Premium dhoop incense sticks for puja and meditation. Rich sandalwood and rose fragrance.",
    price: 40, originalPrice: 45,
    discount: "Rs 5 OFF", weight: "20 pcs", unit: "20 pcs",
    rating: 4.5, ratingCount: 4800, tag: "Puja", sales: 4800,
    tags: ["dhoop", "agarbatti", "incense", "puja", "pooja", "zed black"],
    image: "https://images.unsplash.com/photo-1547571311-6eda4dfc0a12?w=400", stock: 200,
  },
];

async function seed() {
  const uri = process.env.MONGO_URL || process.env.MONGODB_URI || "mongodb://localhost:27017/zepto";
  await mongoose.connect(uri);
  console.log("✅  MongoDB connected");

  let created = 0;
  let skipped = 0;
  let updated = 0;

  for (const p of products) {
    const exists = await Product.findById(p._id);
    if (exists) {
      // Update with new fields (description, unit, ratingCount as number)
      await Product.findByIdAndUpdate(p._id, { $set: p });
      updated++;
      continue;
    }
    await Product.create(p);
    created++;
    console.log(`  ✔  ${p.name}`);
  }

  console.log(`\n📦  Done! ${created} created, ${updated} updated, ${skipped} unchanged.`);
  console.log(`   Total products in seed: ${products.length}`);
  await mongoose.disconnect();
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
